- src/models/volume.js
- src/routes/volume/VolumeList.js
- src/utils/sort.js
https://github.com/rancher/longhorn/issues/97
> Volume page improvement

- src/components/Layout/Header.less
- src/components/Layout/Menu.js
- src/models/engineimage.js
- src/models/volume.js
- src/router.jsx
- src/routes/engineimage/EngineImageList.js
- src/routes/engineimage/detail/EngineImageInfo.js
- src/routes/engineimage/detail/EngineImageInfo.less
- src/routes/engineimage/detail/index.js
- src/routes/volume/EngineUpgrade.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/index.js
- src/routes/volume/index.js
- src/services/engineimage.js
- src/utils/menu.js
https://github.com/rancher/longhorn/issues/95
> Engine Image improvement

- src/models/volume.js
- src/routes/volume/AttachHost.js
- src/routes/volume/EngineUpgrade.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeBulkActions.less
- src/routes/volume/VolumeList.js
- src/routes/volume/index.js
https://github.com/rancher/longhorn/issues/101
> Multiple selection for the volume page

- src/routes/host/HostList.js
https://github.com/rancher/longhorn/issues/103
> API: Rename `status types.NodeState` to `state types.NodeState`

- src/models/snapshot.js
- src/models/volume.js
- src/routes/volume/Snapshots.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/index.js
https://github.com/rancher/longhorn/issues/67
> Add a button in UI to create snapshot then backup in one step

- src/assets/styles/classes.less
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
https://github.com/rancher/longhorn/issues/104#issuecomment-403182198
> Add one additional column Robustness for the volume list and volume detail page

- src/components/Layout/Header.less
- src/components/Layout/Menu.js
- src/utils/menu.js
https://github.com/rancher/longhorn/issues/95#issuecomment-403183946
>  Add General Item Under Setting Menu

- src/routes/volume/detail/index.js
https://github.com/rancher/longhorn/issues/105#event-1721320867
> volume detail page do not show upgrade and attach pop-up when click the corresponding button

- src/models/backup.js
- src/models/engineimage.js
- src/models/volume.js
- src/routes/backup/index.js
- src/routes/engineimage/index.js
- src/routes/volume/index.js
https://github.com/rancher/longhorn-ui/pull/27
> Inbound websocket changes cause user input to be erased 

- src/models/engineimage.js
- src/models/host.js
- src/models/volume.js
- src/routes/volume/VolumeList.js
https://github.com/rancher/longhorn/issues/116
> Refresh the related line instead of the whole volume list table when connected to the websocket

- src/models/engineimage.js
- src/models/host.js
- src/models/volume.js
https://github.com/rancher/longhorn/issues/117
> Deleting the volume doesn't refresh the page automatically

- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
https://github.com/rancher/longhorn/issues/120
> Add `Scheduling Failure` for volume

- src/models/host.js
- src/routes/host/EditDisk.js
- src/routes/host/HostActions.js
- src/routes/host/HostList.js
- src/routes/host/components/EditableDiskCell.js
- src/routes/host/components/EditableDiskTable.js
- src/routes/host/components/EditableDiskTable.less
- src/routes/host/index.js
https://github.com/rancher/longhorn/issues/47
> Edit multiple disk in node page

- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
https://github.com/rancher/longhorn/issues/120
> `Scheduling Failure`  for volume do not show

- src/components/Snapshot/Snapshot.js
- src/components/Snapshot/Snapshot.less
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
https://github.com/rancher/longhorn/issues/110
> Add snapshot detail to the snapshot tree view

- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/helper/index.js
https://github.com/rancher/longhorn/issues/120
> Scheduling failure for volume only when status is False

- src/routes/volume/detail/VolumeInfo.js
https://github.com/rancher/longhorn/issues/125
> Volume Actual Size calculated wrong

- src/routes/host/EditDisk.js
- src/routes/host/HostActions.js
- src/routes/host/HostList.js
- src/routes/host/components/EditableDiskCell.js
- src/routes/host/components/EditableDiskTable.js
https://github.com/rancher/longhorn/issues/124
> Disk edit page improvement

- src/routes/setting/setting.js
https://github.com/rancher/longhorn/issues/126
> Update the general setting to use the new setting API

- src/routes/host/components/EditableDiskCell.js
https://github.com/rancher/longhorn/issues/124
> change path placeholder and set storage min value to 0

- src/components/DropOption/DropOption.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/index.js
- src/routes/volume/index.js
https://github.com/rancher/longhorn/issues/127
> Tweak for Upgrade

- src/routes/host/components/EditableDiskCell.js
> Fix storageReserve minimal

- src/routes/setting/setting.js
- src/routes/setting/setting.less
- src/routes/volume/VolumeList.js
https://github.com/rancher/longhorn/issues/131
> API changes for attached node and endpoint, and setting

- src/assets/styles/antd-customize/generic.less
- src/routes/backup/BackupList.js
- src/routes/host/HostList.js
- src/routes/volume/VolumeList.js
- src/utils/sort.js
https://github.com/rancher/longhorn/issues/128
> Allow sorting in the Node, Volume, Backup page

- src/routes/backup/BackupList.js
- src/routes/host/HostList.js
- src/routes/volume/CreateVolume.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
- src/routes/volume/helper/index.js
https://github.com/rancher/longhorn/issues/157
> Page tweaks

- src/assets/styles/antd-customize/generic.less
- src/routes/host/components/EditableDiskItem.js
- src/routes/host/components/StorageInput.js
- src/routes/setting/setting.js
https://github.com/rancher/longhorn/issues/156
> Setting page tweak for read-only option

- src/components/Snapshot/Snapshot.js
- src/routes/volume/Snapshots.js
- src/utils/backup.js
https://i.imgur.com/F5TZoPg.png
> Create info modal when create backup is clicked

- src/routes/host/EditDisk.js
- src/routes/host/components/EditableDiskItem.js
- src/routes/host/components/EditableDiskList.js
- src/routes/host/components/PathInput.js
- src/routes/host/helper/index.js
https://github.com/rancher/longhorn/issues/170
> filter out same directory when edit disks on node

- src/routes/volume/VolumeBulkActions.js
https://github.com/rancher/longhorn/issues/179
> Batch detach should be allowed if volume is in attaching state

- src/routes/host/DiskList.js
- src/routes/host/HostList.js
https://github.com/rancher/longhorn/issues/192
>  If one node has been disabled, all it's disks should be in the disabled

- src/routes/volume/index.js
https://github.com/rancher/longhorn/issues/190
> Volume node filter doesn't work

- src/components/Filter/Filter.js
- src/routes/engineimage/index.js
- src/utils/filter.js
https://github.com/rancher/longhorn/issues/195
> change engine image filter and rename create button label

- src/routes/volume/VolumeList.js
- src/utils/formater.js
https://github.com/rancher/longhorn/issues/196
> The timestamp doesn't show in firefox/safari

- src/routes/host/DiskList.less
- src/routes/host/HostActions.js
- src/routes/host/HostList.js
- src/routes/host/components/StorageInfo.less
https://github.com/rancher/longhorn/issues/197
> Node Tab At 4:3 Aspect Ratio

- src/components/Replica/Replica.js
- src/models/host.js
- src/routes/host/DiskList.js
- src/routes/host/DiskList.less
- src/routes/host/HostList.js
- src/routes/host/index.js
- src/routes/volume/detail/index.js
https://github.com/rancher/longhorn/issues/188
> Replica should be associated with the disk as well

- src/routes/engineimage/index.js
- src/routes/host/index.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
https://github.com/rancher/longhorn/issues/213
> clear page blur after close modal

- src/routes/volume/CreateVolume.js
1. volume number of replica limit 2 to 10 and must be a positive integer
2. The volume size must be greater than 0
> Form validation

- package.json
- src/components/Layout/Footer.js
- src/models/eventlog.js
- src/router.jsx
- src/routes/dashboard/components/eventLogs.js
- src/routes/dashboard/components/eventLogs.less
- src/routes/dashboard/components/resourceChart.js
- src/routes/dashboard/components/resourceOverview.js
- src/routes/dashboard/components/resourceOverview.less
- src/routes/dashboard/index.js
- src/services/eventlog.js
- src/utils/sort.js
https://github.com/rancher/longhorn/issues/186
Tested with backend https://github.com/rancher/longhorn-manager/pull/172
> Add event log to the dashboard

- src/routes/dashboard/components/eventLogs.js
https://github.com/rancher/longhorn/issues/186#issuecomment-413754901
> remove the sort of message, and sort by the field of last seen default

- src/components/Replica/Replica.js
- src/components/Replica/ReplicaList.js
- src/routes/volume/Salvage.js
- src/routes/volume/Salvage.less
- src/routes/volume/detail/index.js
https://github.com/rancher/longhorn/issues/238
> Volume detail page salvage button cannot be clicked

- src/components/Snapshot/Snapshot.js
- src/models/snapshot.js
- src/routes/volume/Snapshots.js
https://github.com/rancher/longhorn/issues/201
> Volume detail page doesn't get refreshed for new snapshots

- src/models/backup.js
- src/models/eventlog.js
- src/models/host.js
- src/models/volume.js
- src/routes/backup/BackupList.js
- src/routes/backup/index.js
- src/routes/dashboard/components/eventLogs.js
- src/routes/dashboard/index.js
- src/routes/host/HostList.js
- src/routes/host/index.js
- src/routes/volume/VolumeList.js
- src/routes/volume/index.js
- src/utils/store.js
https://github.com/rancher/longhorn/issues/237
> Cache user specified sorting order

- src/models/snapshot.js
- src/routes/volume/detail/Snapshots.js
- src/services/volume.js
- src/utils/request.js
https://github.com/rancher/longhorn/issues/248
> Snapshot tree disappeared from time to time

- src/assets/styles/antd-customize/generic.less
- src/routes/host/HostActions.js
- src/routes/host/HostList.js
- src/routes/host/components/EditableDiskItem.js
- src/routes/host/index.js
issue: 
1. https://github.com/rancher/longhorn/issues/249
2. radio icon and label are not aligned in edit disks modal
3. tooltip not show when disk not allow delete in edit disks modal
> Node status is down, editing is not allowed and  radio icon and label are not aligned

- src/assets/styles/antd-customize/generic.less
- src/components/DropOption/DropOption.js
- src/components/Replica/Replica.js
- src/components/Replica/ReplicaList.js
- src/models/host.js
- src/models/volume.js
- src/routes/host/HostActions.js
- src/routes/host/HostList.js
- src/routes/host/HostReplica.js
- src/routes/host/ReplicaActions.js
- src/routes/host/ReplicaList.js
- src/routes/host/index.js
- src/routes/volume/detail/index.js
- src/services/host.js
https://github.com/rancher/longhorn/issues/306
> Improve Node UX

- src/routes/setting/setting.js
https://github.com/rancher/longhorn/issues/312
- Use checkbox for setting values of bool type
> Upgrade checker support

- package.json
- src/components/Layout/Footer.js
> Add semantic version comparison

- Makefile
To be consistent with other components.
> build: Make `REPO` `rancher` rather than `longhorn-ui`

- src/models/volume.js
- src/routes/volume/UpdateReplicaCount.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/index.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
https://github.com/rancher/longhorn/issues/359
> support changing to 'numberOfReplicas'

- src/components/Snapshot/Snapshot.js
- src/routes/volume/detail/Snapshots.js
- src/routes/volume/helper/index.js
https://github.com/rancher/longhorn/issues/343
> volume detail page: disable volume snapshot operations when upgrade or migration in process

- src/components/Layout/Footer.js
https://github.com/rancher/longhorn/issues/84
> add a link of Generate Support Bundle at the bottom bar

- src/routes/setting/setting.js
https://github.com/rancher/longhorn/issues/402
> Setting page may be reloaded when there are user inputs

- src/routes/volume/CreateVolume.js
- src/utils/filter.js
https://github.com/rancher/longhorn/issues/400
>  False alarm on limited node redundancy for failed replica  and limit volume replica num 1 to 10

- src/utils/filter.js
https://github.com/rancher/longhorn/issues/405
> Need to add upgrade icon for detached volume as well

- src/components/Layout/Footer.js
https://github.com/rancher/longhorn/issues/406
> Generate support bundle doesn't work behind Rancher Proxy

- src/routes/volume/detail/index.js
- src/routes/volume/index.js
https://github.com/rancher/longhorn/issues/407
> Click volume->backups or volume details -> backups won't jump to the backup page

- package.json
- src/assets/styles/antd-customize/generic.less
- src/assets/styles/antd-customize/selectDropdown.less
- src/assets/styles/antd-customize/tree.less
- src/components/Filter/Filter.js
https://github.com/rancher/longhorn/issues/457
> update antd to v2.13.11

- src/assets/styles/antd-customize/tree.less
- src/models/backup.js
- src/router.jsx
- src/routes/backup/BackupDetail.js
- src/routes/backup/BackupFilter.js
- src/routes/backup/BackupVolumeList.js
- src/routes/backup/index.js
https://github.com/rancher/longhorn/issues/460
> make backup volume page to be two levels

- src/models/backup.js
- src/routes/backup/index.js
Fix backup filter Caching Problem
> Fix backup filter Caching Problem

- src/components/Layout/Footer.js
Add logical judgment to View version validity
> Fixed an error due to semver

- src/assets/styles/antd-customize/tree.less
- src/components/ModalBlur/ModalBlur.js
- src/models/volume.js
- src/routes/volume/VolumeList.js
- src/routes/volume/VolumeList.less
- src/routes/volume/WorkloadDetailModal.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/index.js
https://github.com/rancher/longhorn/issues/461
> Fixed the workload/pod field 

- src/assets/styles/antd-customize/tree.less
- src/routes/engineimage/EngineImageList.js
add Reference Count,Last Reference At to engine image list
> Add fields to the engine list

- src/components/Schedule/Schedule.js
- src/models/volume.js
- src/routes/volume/CreatePVAndPVCSingle.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/WorkloadDetailModal.js
- src/routes/volume/detail/RecurringList.js
- src/routes/volume/index.js
https://github.com/rancher/longhorn/issues/490
> Volume overview page improvement

- src/components/Snapshot/Snapshot.js
- src/models/snapshot.js
https://github.com/rancher/longhorn/issues/497
> Distinguish a normal snapshot from by system or deleted snapshot

- src/routes/volume/VolumeList.js
- src/utils/sort.js
https://github.com/rancher/longhorn/issues/461
> Add Namespace between PV/PVC and Pod

- src/routes/backup/BackupVolumeList.js
https://github.com/rancher/longhorn/issues/459
> Add Last Backup At field

- src/routes/volume/VolumeList.js
https://github.com/rancher/longhorn/issues/461
> change volumeList th size

- .eslintignore
- .eslintrc
- package.json
- src/assets/styles/antd-customize/selectDropdown.less
- src/components/ReactCron/ReactCron.js
- src/components/ReactCron/ReactCron.less
- src/components/Replica/Replica.js
- src/components/index.js
- src/routes/volume/SnapshotDetailModal.js
- src/routes/volume/detail/RecurringList.js
- src/utils/prettycron.js
https://github.com/rancher/longhorn/issues/504
> Change the cron expression component

- package.json
- src/main.js
- src/routes/volume/VolumeList.js
https://github.com/rancher/longhorn/issues/509
> Fix Url hash and use text Instead of Icon

- .webpackrc.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/RecurringList.js
- src/routes/volume/detail/index.js
- src/utils/prettycron.js
https://github.com/rancher/longhorn/issues/510
> Merge the State with Health. Name the new field State

- src/routes/host/HostFilter.js
- src/routes/host/HostList.less
https://github.com/rancher/longhorn/issues/516
> Change the color of green bar in the node page to #27AE5F

- src/models/backup.js
https://github.com/rancher/longhorn/issues/515
> Dispatch the backup model query only in backup page

- src/components/Layout/BundlesModel.js
- src/components/Layout/Footer.js
- src/components/ModalBlur/ModalBlur.js
- src/models/app.js
- src/routes/app.js
- src/services/app.js
https://github.com/rancher/longhorn/issues/414
> Change download the support bundle API

- src/components/Icon/IconStandBackup.js
- src/components/ModalBlur/ModalBlur.js
- src/models/app.js
- src/models/backup.js
- src/models/engineimage.js
- src/models/host.js
- src/models/volume.js
- src/routes/backup/BackupList.js
- src/routes/backup/BackupVolumeList.js
- src/routes/backup/CreateStandbyVolume.js
- src/routes/backup/index.js
- src/routes/volume/ChangeVolumeModal.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/index.js
- src/services/backup.js
- src/services/volume.js
https://github.com/rancher/longhorn/issues/495
> Create Disaster Recovery Volume

- src/routes/backup/BackupList.js
- src/routes/backup/BackupVolumeList.js
- src/routes/host/HostList.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeList.js
https://github.com/rancher/longhorn/issues/524
> Fixed create PV/PVC bug and Change the way the list scrolls

- src/components/Layout/BundlesModel.js
- src/components/Layout/Footer.js
- src/models/app.js
Add progress to the Bundle support dialog
> Add progress to the Bundle support dialog

- src/routes/backup/BackupList.js
- src/routes/backup/BackupVolumeList.js
- src/routes/dashboard/components/eventLogs.less
- src/routes/host/DiskList.js
- src/routes/host/HostList.js
- src/routes/volume/VolumeList.js
Fixed setting 'scroll' attribute for table causes header to be misaligned
> Fixed table-header misalignment bug

- src/models/app.js
- src/routes/volume/VolumeList.js
Modify the volume list header size
> Modify the volume list header size

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/index.js
- src/routes/volume/index.js
https://github.com/rancher/longhorn/issues/534
> Add restoring process state to the volume list

- src/assets/styles/antd-customize/tree.less
- src/routes/volume/VolumeBulkActions.js
- src/utils/backup.js
https://github.com/rancher/longhorn/issues/540
> Notice Backup In Progress may take a while depending

- src/components/Replica/Replica.js
https://github.com/rancher/longhorn/issues/547
> Show replicas datapath as a tooltip to the Node

- src/assets/styles/antd-customize/generic.less
- src/routes/setting/setting.less
https://github.com/rancher/longhorn/issues/550
> Fixed units misaligned bug in the disk page

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/WorkloadDetailModal.js
- src/routes/volume/detail/VolumeInfo.js
https://github.com/rancher/longhorn/issues/551
> Change Kubernetes status name after deleting PVC and workload

- src/components/ReactCron/ReactCron.js
- src/routes/volume/detail/RecurringList.js
https://github.com/rancher/longhorn/issues/504
> Optimize cron expressions

- src/models/backup.js
- src/models/volume.js
- src/router.jsx
- src/routes/notfound/index.js
https://github.com/rancher/longhorn/issues/555
> Fix rancher proxy

- src/routes/volume/detail/RecurringList.js
https://github.com/rancher/longhorn/issues/504
> Restore the cron expression

- src/routes/host/components/EditableDiskItem.js
https://github.com/rancher/longhorn/issues/550
> Fixed radio button misaligned

- src/components/Schedule/Schedule.js
- src/models/app.js
- src/routes/volume/detail/Snapshots.js
https://github.com/rancher/longhorn/issues/559
> Fixed support bundle 404 bug when rancher proxy

- src/routes/backup/BackupList.js
Modify backups list header field
> Modify backups list header field

- src/routes/backup/RestoreBackup.js
https://github.com/rancher/longhorn/issues/562
> Change the min number of replicas to 1

- src/models/app.js
https://github.com/rancher/longhorn/issues/575
> Fix Support bundle download doesn't work in the volume detail page

- src/components/Filter/Filter.less
- src/routes/volume/index.js
- src/utils/filter.js
https://github.com/rancher/longhorn/issues/577
> Add able to filter volumes by namespace in the volumes list

- src/routes/volume/VolumeList.js
https://github.com/rancher/longhorn/issues/579
> Change volume page fixed the action menu

- src/assets/styles/antd-customize/tree.less
- src/components/Snapshot/Snapshot.js
- src/routes/volume/detail/Snapshots.js
- src/routes/volume/detail/index.js
https://github.com/longhorn/longhorn/issues/45
> Add progress report for backup

- src/models/backup.js
https://github.com/longhorn/longhorn/issues/601
> Change the routing matching rules for loading backup model

- src/models/host.js
- src/models/volume.js
- src/routes/host/DiskList.js
- src/routes/host/EditDisk.js
- src/routes/host/HostActions.js
- src/routes/host/HostList.js
- src/routes/host/components/EditableDiskItem.js
- src/routes/host/components/EditableDiskItem.less
- src/routes/host/components/EditableDiskList.js
- src/routes/host/components/TagComponent.js
- src/routes/host/index.js
- src/routes/volume/CreateVolume.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/index.js
- src/services/volume.js
https://github.com/longhorn/longhorn/issues/311
> support for storage pools

- src/routes/setting/setting.js
https://github.com/longhorn/longhorn/issues/607
> Change form item layout make checkbox go up adjacent to the text

- src/components/Snapshot/Snapshot.js
- src/routes/volume/detail/Snapshots.js
https://github.com/longhorn/longhorn/issues/45
> Fix react render all the time in snapshot page

- src/components/ReactCron/ReactCron.js
- src/routes/volume/SnapshotDetailModal.js
- src/routes/volume/detail/RecurringList.js
- src/utils/cronValidate.js
https://github.com/longhorn/longhorn/issues/504
> Add cron expression validate

- src/components/Snapshot/Snapshot.js
https://github.com/longhorn/longhorn/issues/628
> Shows based on the average of backups progress

- Dockerfile
- src/models/volume.js
- src/routes/volume/AttachHost.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/629
> Add new field ‘disableFrontend’ when Attach host

- src/components/BackupLabelInput/BackupLabelInput.js
- src/components/BackupLabelInputForRecurring/BackupLabelInputForRecurring.js
- src/components/Snapshot/Snapshot.js
- src/components/index.js
- src/models/backup.js
- src/models/snapshot.js
- src/models/volume.js
- src/routes/backup/BackupDetail.js
- src/routes/backup/BackupList.js
- src/routes/backup/ShowBackupLabels.js
- src/routes/volume/CreatePVAndPVCSingle.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/detail/CreateBackupModal.js
- src/routes/volume/detail/RecurringList.js
- src/routes/volume/detail/Snapshots.js
- src/routes/volume/detail/index.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/563
> User can create multiple backup labels

- src/models/backup.js
- src/routes/backup/BackupVolumeList.js
- src/routes/backup/index.js
- src/services/backup.js
https://github.com/longhorn/longhorn/issues/598
> Add action to delete all the backups of one volume

- src/routes/volume/CreateVolume.js
https://github.com/longhorn/longhorn/issues/650
> Disable base image feature for now

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/662
> Disabled detach action for DR volume

- src/components/Layout/BundlesModel.js
https://github.com/longhorn/longhorn/issues/652
> Add validation rules for support bundle's issue description

- .drone.yml
> Add droneci config

- src/components/Replica/Replica.js
- src/components/Replica/ReplicaList.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/RecurringList.js
- src/routes/volume/detail/Snapshots.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
https://github.com/longhorn/longhorn/issues/49
> Add progress for restore

- src/components/Layout/BundlesModel.js
https://github.com/longhorn/longhorn/issues/652
> Add validation of space

- src/routes/host/HostActions.js
Allow user to disable the scheduling when the node is down
> Allow user to disable the scheduling when the node is down

- src/routes/backup/RestoreBackup.js
Fix no alignment bug for Resotre modal
> Fix no alignment bug for Resotre modal

- src/routes/backup/CreateStandbyVolume.js
https://github.com/longhorn/longhorn/issues/650
> Removed Base Image from Create Disaster Recovery Volume modal

- src/models/host.js
- src/routes/host/DiskList.js
- src/routes/host/HostList.js
- src/routes/host/components/InstanceManagerComponent.js
- src/routes/host/index.js
- src/services/host.js
https://github.com/longhorn/longhorn/issues/657
> Add the status of instance managers  to host list

- src/models/volume.js
https://github.com/longhorn/longhorn/issues/648
> Stop websocket updates when data is not up-to-date

- src/models/volume.js
https://github.com/longhorn/longhorn/issues/648
> Change the ws delay update logic

- .eslintrc
- src/assets/styles/antd-customize/tree.less
- src/components/Replica/Replica.js
- src/components/Replica/ReplicaList.js
- src/components/Snapshot/Snapshot.js
- src/models/snapshot.js
- src/routes/volume/detail/Snapshots.js
- src/routes/volume/detail/index.js
https://github.com/longhorn/longhorn/issues/665
> Show progress when deleting snapshot

- package.json
- src/routes/volume/detail/RecurringList.js
https://github.com/longhorn/longhorn/issues/699
> Fix Text overflow when the label is too long

- src/routes/host/components/EditableDiskItem.js
- src/routes/host/components/EditableDiskItem.less
- src/routes/host/components/EditableDiskList.js
https://github.com/longhorn/longhorn/issues/719
> Fix the bug node tags will mess up Longhorn UI

- src/models/backup.js
https://github.com/longhorn/longhorn/issues/748
> Fix the rules of dva modal request matching

- src/components/Layout/Menu.js
- src/components/LinkTo/LinkTo.js
- src/models/backup.js
- src/routes/backup/index.js
- src/routes/dashboard/components/numberCard.js
- src/routes/engineimage/EngineImageList.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/index.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/764
> Pass in the state parameter when routing to the backup page

- src/components/Snapshot/Snapshot.js
- src/routes/volume/detail/Snapshots.js
https://github.com/longhorn/longhorn/issues/773
> Fix the bug System Hidden button doesn't work in volume detail page

- src/components/Snapshot/Snapshot.js
https://github.com/longhorn/longhorn/issues/781
> Fix the bug volume-head disappeared at recurring snapshot create

- src/routes/dashboard/index.js
https://github.com/longhorn/longhorn/issues/825
> Format the data returned by eventlog api

- src/routes/backup/BackupDetail.js
https://github.com/longhorn/longhorn/issues/824
> feat(Backup detail) Add actions for whole backup volume

- src/routes/backup/BackupList.js
- src/routes/backup/BackupVolumeList.js
- src/routes/backup/index.js
https://github.com/longhorn/longhorn/issues/837
> Fix(backup page) remove base image from backup page

- src/routes/volume/detail/VolumeInfo.js
> fix(volume info) Adds judgment when controllers is null

- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/842
> fix(volume info) Adds judgment when selectnode is null

- src/assets/styles/antd-customize/tree.less
- src/models/snapshot.js
https://github.com/longhorn/longhorn/issues/839
> fix(snapshot) Fix the style to make it a tree node

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/884
> Fix(actions) Disabled upgrade button when the volume is not detached

- src/models/backup.js
- src/routes/backup/BackupDetail.js
- src/routes/backup/BackupList.js
- src/routes/backup/backupList.less
- src/routes/volume/VolumeList.js
https://github.com/longhorn/longhorn/issues/883
> Feat(backup list) show workload info in the backup list

- src/components/Snapshot/Snapshot.js
- src/components/Snapshot/Snapshot.less
- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/897
> Fix(snapshot) Fix the snapshot reverting message

- src/models/volume.js
- src/routes/volume/CreatePVAndPVCSingle.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/932
> feat(create pvc) Use Previous PVC by default

- src/models/backup.js
- src/routes/backup/BackupBulkActions.js
- src/routes/backup/BackupBulkActions.less
- src/routes/backup/BackupDetail.js
- src/routes/backup/BackupVolumeList.js
- src/routes/backup/RestoreBackup.js
- src/routes/backup/index.js
https://github.com/longhorn/longhorn/issues/933
https://github.com/longhorn/longhorn/issues/934
https://github.com/longhorn/longhorn/issues/935
> feat(backup) Add bulk action restore latest backups

- src/routes/backup/BackupList.js
- src/routes/volume/VolumeList.js
- src/routes/volume/index.js
- src/utils/filter.js
- src/utils/sort.js
https://github.com/longhorn/longhorn/issues/940
https://github.com/longhorn/longhorn/issues/936
https://github.com/longhorn/longhorn/issues/937
> feat(volume) Suport volume sort by PV/PVC

- src/components/Snapshot/Snapshot.js
- src/routes/backup/BackupList.js
- src/routes/backup/RestoreBackup.js
- src/routes/dashboard/components/eventLogs.js
- src/routes/dashboard/components/eventLogs.less
- src/routes/volume/VolumeList.js
- src/utils/index.js
https://github.com/longhorn/longhorn/issues/921
https://github.com/longhorn/longhorn/issues/917
https://github.com/longhorn/longhorn/issues/883
> Fix(Restore backup) Add trim method for RestoreBackup’s name strings

- src/models/backup.js
- src/routes/backup/BackupDetail.js
- src/routes/backup/RestoreBackup.js
- src/routes/backup/index.js
- src/services/backup.js
https://github.com/longhorn/longhorn/issues/939
> feat(restore backup) Add NodeTags and DiskTags when restore backup

- src/components/ModalBlur/ModalBlur.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/944
https://github.com/longhorn/longhorn/issues/942
> feat(key down) Hold CTRL to bypass confirmation

- src/models/volume.js
- src/routes/volume/ExpansionVolumeSizeModal.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/VolumeList.less
- src/routes/volume/detail/ExpansionVolumeSizeModal.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/VolumeInfo.less
- src/routes/volume/detail/index.js
- src/routes/volume/index.js
- src/services/volume.js
https://github.com/longhorn/longhorn/issues/977
> feat(volume expansion) Add operation Expand for the volume

- src/routes/volume/RecurringList.js
- src/routes/volume/SnapshotDetailModal.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/index.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/953
> feat(snpshot) Add a modal to edit cron expressions

- src/routes/host/EditDisk.js
- src/routes/host/HostList.js
- src/routes/host/components/EditableDiskItem.js
- src/routes/host/components/EditableDiskItem.less
- src/routes/host/components/EditableDiskList.js
- src/routes/host/index.js
- src/routes/volume/index.js
- src/utils/filter.js
https://github.com/longhorn/longhorn/issues/958
https://github.com/longhorn/longhorn/issues/959
> Feat(Node tag) Add a tag filter for node and volume page

- src/components/Layout/Bread.js
- src/routes/backup/BackupList.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/967
https://github.com/longhorn/longhorn/issues/980
> Fix(volume list) Optimize the volume list page

- src/components/Filter/Filter.js
- src/models/volume.js
- src/routes/volume/RecurringBulkList.js
- src/routes/volume/SnapshotBulkModal.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/detail/RecurringList.js
- src/routes/volume/detail/Snapshots.js
- src/routes/volume/detail/index.js
- src/routes/volume/detail/index.less
- src/routes/volume/index.js
- src/utils/filter.js
https://github.com/longhorn/longhorn/issues/946
> feat(bulk schedule) Add multiple volumes backup schedule

- src/routes/host/DiskList.js
- src/routes/host/index.js
https://github.com/longhorn/longhorn/issues/988
> fix(disk modal) Fix unable to delete replica from detached volume

- src/models/host.js
- src/routes/host/HostBulkActions.js
- src/routes/host/HostBulkActions.less
- src/routes/host/HostFilter.js
- src/routes/host/HostList.js
- src/routes/host/ReplicaList.js
- src/routes/host/index.js
https://github.com/longhorn/longhorn/issues/949
https://github.com/longhorn/longhorn/issues/1015
> feat(Node) Add bulk auto delete node action in node list page

- src/assets/styles/antd-customize/tree.less
- src/models/snapshot.js
https://github.com/longhorn/longhorn/issues/1010
> Fix(snapshot) Fix the bug ui can’t create snapshot

- src/components/Filter/Filter.js
- src/routes/volume/RecurringBulkList.js
- src/routes/volume/RecurringList.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/1023
https://github.com/longhorn/longhorn/issues/946
> feat(volume) Add PV status filter in volume list page

- src/models/snapshot.js
- src/routes/backup/BackupVolumeList.js
- src/routes/backup/index.js
- src/routes/host/HostList.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/Snapshots.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/1022
> Feat(volume) Clicking row selects it And fix snapshot modal

- src/components/Replica/Replica.js
- src/models/backup.js
- src/routes/backup/index.js
- src/routes/host/HostList.js
https://github.com/longhorn/longhorn/issues/1048
https://github.com/longhorn/longhorn/issues/929
> feat(zone) Show k8s zone and region tags

- src/routes/volume/detail/Snapshots.js
> fix(create backup) Change the tooltip message for DR VOLUME

- src/components/Layout/BundlesModel.js
> fix(css) Take out green check mark when generate Support Bundle

- src/components/Filter/Filter.js
- src/models/host.js
- src/routes/engineimage/index.js
- src/routes/host/HostList.js
- src/routes/host/components/InstanceManagerComponent.js
- src/routes/host/index.js
- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/1028
https://github.com/longhorn/longhorn/issues/1077
> fix(node) Fix node Readiness column and update Instance Manager Dialog

- src/routes/host/ReplicaList.js
- src/routes/host/index.js
https://github.com/longhorn/longhorn/issues/1084
> fix(replicas) Fix the bug return data without removeUrl

- src/models/volume.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/1089
https://github.com/longhorn/longhorn/issues/1088
> feat(expend volume) Support bulk operation

- src/models/snapshot.js
- src/routes/host/components/InstanceManagerComponent.js
- src/utils/sort.js
https://github.com/longhorn/longhorn/issues/1082
> Fix(snapshot) Add json format judgments

- src/models/volume.js
- src/routes/volume/CreatePVAndPVC.js
- src/routes/volume/CreatePVAndPVCSingle.js
https://github.com/longhorn/longhorn/issues/1135
> Feat(PV) Supports selecting file system type when creating PV

- src/routes/host/DiskList.js
- src/routes/host/EditDisk.js
- src/routes/host/components/EditableDiskItem.js
- src/routes/host/components/EditableDiskList.js
https://github.com/longhorn/longhorn/issues/972
> feat(Disks) Changed DiskUpdate Api parameter type from Array to Object

- src/components/Snapshot/Snapshot.js
[FEATURE] Add replica name to the backup status
issue:
https://github.com/longhorn/longhorn/issues/1166
> feat(backup status): add replica field

- src/models/backup.js
- src/models/volume.js
- src/routes/volume/BulkChangeVolumeModal.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/index.js
feat(volume, backup): 
1. add Activate DR volume to batch operation 
2. don't jump to volume page after create DR volume
Linked Issues：
https://github.com/longhorn/longhorn/issues/1171
> feat(volume, backup): add Activate DR volume to batch operation

- src/models/backup.js
- src/routes/backup/BackupBulkActions.js
- src/routes/backup/BulkCreateStandbyVolumeModal.js
- src/routes/backup/index.js
feat(backup): add create DR volume to bacth operation
> feat(backup): add create DR volume to bacth operation

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
fix(volume):  enable the upgrade button when the volume is attached
Enable live upgrade from v0.8.0 to v0.8.1
Linked issue：
https://github.com/longhorn/longhorn/issues/1195
> fix(volume):  enable the upgrade button when the volume is attached

- src/components/Replica/Replica.js
- src/routes/backup/BackupList.js
- src/routes/host/HostList.js
fix(node, volume-detail): fix text error and add tooltip for rebuilding replica
Linked Issues:
https://github.com/longhorn/longhorn/issues/1167
https://github.com/longhorn/longhorn/issues/1204  issue-#3
> fix(node, volume-detail): fix text error and add tooltip for rebuilding replica

- src/components/ExpansionErrorDetail/ExpansionErrorDetail.js
- src/components/Replica/Replica.js
- src/components/index.js
- src/models/backup.js
- src/models/volume.js
- src/routes/backup/index.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/index.js
- src/services/volume.js
https://github.com/longhorn/longhorn/issues/978
> Feat(Cancel Expansion) Add cancel expansion operation

- src/routes/backup/BackupVolumeList.js
https://github.com/longhorn/longhorn/issues/1199
image: wangsiye/longhorn-ui:c45d726
> Display backup error information on the backup list page

- src/routes/volume/detail/EventList.js
- src/routes/volume/detail/index.js
longhorn/longhorn#990
image: wangsiye/longhorn-ui:c45d726
> Show volume related events in the volume details

- src/routes/backup/BackupBulkActions.js
- src/routes/backup/BackupVolumeList.js
- src/routes/host/components/EditableDiskItem.js
- src/utils/filter.js
1. Fix node is still schedulable When there are disks with disabled scheduling and invalid disks
2. Resotre last backup is disabled when an error occurs in the backup file
3. Fixed the field style of Edit Node and Disks popup
https://github.com/longhorn/longhorn/issues/1201
https://github.com/longhorn/longhorn/issues/1211
https://github.com/longhorn/longhorn/issues/1290
image: wangsiye/longhorn-ui:187f116
> Fix issues 1290 1211 1201

- src/routes/dashboard/components/eventLogs.js
https://github.com/longhorn/longhorn/issues/1198
image: wangsiye/longhorn-ui:79c09d9
> (Fix dashboard) Add source field ordering for dashboard list

- src/routes/backup/BackupList.js
image: wangsiye/longhorn-ui:79c09d9
https://github.com/longhorn/longhorn/issues/1321
https://github.com/longhorn/longhorn/issues/1320
> Show error and disable restore when there is Invalid backup file in S3

- src/routes/backup/BackupDetail.js
- src/routes/backup/BackupVolumeList.js
- src/routes/dashboard/components/eventLogs.js
Replace drop-down menu text 'No Last Backup'
image:wangsiye/longhorn-ui:8de351f
https://github.com/longhorn/longhorn/issues/1319
https://github.com/longhorn/longhorn/issues/1338
> Fix event log search button remains consistent

- src/components/Snapshot/Snapshot.js
- src/routes/backup/BackupList.js
- src/routes/backup/ShowBackupLabels.js
- src/routes/backup/index.js
- src/routes/volume/WorkloadDetailModal.js
https://github.com/longhorn/longhorn/issues/1194
https://github.com/longhorn/longhorn/issues/1299
https://github.com/longhorn/longhorn/issues/1317
https://github.com/longhorn/longhorn/issues/1316
image: wangsiye/longhorn-ui:8de351f
> Add timestamp for Workload / Pod and Labels in backup list page

- src/routes/host/DiskList.js
- src/utils/filter.js
https://github.com/longhorn/longhorn/issues/1287
image: wangsiye/longhorn-ui:941d022
> fix(node status) change node status to reflect that it has been cordoned

- src/routes/setting/setting.js
- src/routes/setting/setting.less
- src/routes/volume/ConfirmModalWithWorkload.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/index.js
2. fix(volume) Presented a warning message when detach a volume which is currently used by a workload
3. fix(settings) Change a red frame for the Danger Zone settings
https://github.com/longhorn/longhorn/issues/1350
https://github.com/longhorn/longhorn/issues/1357
https://github.com/longhorn/longhorn/issues/1318
https://github.com/longhorn/longhorn/issues/1356
image: wangsiye/longhorn-ui:941d022
> 1. fix(volume) Remove the yellow background for the column Attached to

- src/models/snapshot.js
- src/routes/host/components/EditableDiskItem.js
- src/routes/host/components/EditableDiskList.js
- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/1359
image: wangsiye/longorn-ui:3f5515c
> feat(conditions) Show up the volume, node, disk conditions

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/utils/cronValidate.js
https://github.com/longhorn/longhorn/issues/1383
image: wangsiye/longhorn-ui:afa7e56
> fix(cron) Fix cron expression verification logic

- src/models/backup.js
https://github.com/longhorn/longhorn/issues/1382
image: wangsiye/longhorn-ui:afa7e56
> fix(backup) Forbid requesting interface '/backup/volumes' on first load

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/1373
image: wangsiye/longhorn-ui:ff585c6
> fix(expand volume) Fix the conditions for expanding volume size

- src/models/host.js
https://github.com/longhorn/longhorn/issues/1377
image: wangsiye/longhorn-ui:ff585c6
> Fix(host replica) Fix the bug that the pop-up window data is not reset

- src/assets/styles/antd-customize/generic.less
- src/routes/backup/BackupList.js
- src/routes/backup/BackupVolumeList.js
- src/routes/host/HostList.js
- src/routes/volume/VolumeList.js
- src/routes/volume/index.js
> feat(page) Support front-end paging

- src/assets/styles/antd-customize/tree.less
- src/routes/backup/BackupDetail.js
- src/routes/backup/BackupList.js
- src/routes/backup/index.js
- webpack.config.production.js
https://github.com/longhorn/longhorn/issues/1396
image: wangsiye/longhorn-ui:93d4b65
> fix(backup) Prompt warning message when deleting backup

- src/assets/styles/antd-customize/generic.less
- src/models/backup.js
- src/routes/host/DiskList.js
- src/routes/host/HostList.js
- src/routes/host/index.js
- src/routes/volume/VolumeList.js
https://github.com/longhorn/longhorn/issues/1405
> fix(page) Keep the pagination position at the bottom of the page

- src/routes/volume/VolumeActions.js
https://github.com/longhorn/longhorn/issues/1414
image:wangsiye/longhorn-ui:af24898
> fix(volume) Disable Update Replica Count button for DR volumes

- src/assets/styles/antd-customize/generic.less
- src/routes/backup/BackupList.js
- src/routes/backup/BackupVolumeList.js
- src/routes/host/HostList.js
- src/routes/volume/VolumeList.js
https://github.com/longhorn/longhorn/issues/1426
image:wangsiye/longhorn-ui:af45a6d
> fix(table) Limit the maximum height of a specific table

- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/1420
wangsiye/longhorn-ui:6771633
> fix(Drvolume) Disable batch update schedule options for Dr volume

- src/components/Snapshot/Snapshot.js
https://github.com/longhorn/longhorn/issues/1427
wangsiye/longhorn-ui:6771633
> fix(revert) Fix bug that 'revet' is diabled but can still send requests

- src/models/backup.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
image: wangsiye/longhorn-ui:f661000
https://github.com/longhorn/longhorn/issues/1441
> Fix(volume) Modify the logic of disabling upgrade engine

- package.json
- src/assets/styles/index.less
- src/assets/styles/markdown-customize/markdown.less
- src/routes/setting/setting.js
- src/routes/setting/setting.less
https://github.com/longhorn/longhorn/issues/1374
image: wangsiye/longhorn-ui:4fa81ea
> feat(markdown) Import makrdown to display settings description

- src/assets/styles/antd-customize/generic.less
- src/routes/setting/setting.js
image: wangsiye/longhorn-ui:81aeabf
https://github.com/longhorn/longhorn/issues/1484
> fix(settings) Adjust settings details style

- src/utils/filter.js
https://github.com/longhorn/longhorn/issues/1518
image: wangsiye/longhorn-ui:bfe66b1
> fix(dashborad) Fix the bug that the node chart is displayed incorrectly

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/1520
image: wangsiye/longhorn-ui:b1970df
> fix(upgrade) Enable live upgrade option in longhorn

- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/VolumeInfo.less
- src/routes/volume/detail/index.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/1451
image: wangsiye/longhorn-ui:0bc7973
> fix(volume) Show error message for volume when the attached node is down

- Dockerfile
https://github.com/longhorn/longhorn/issues/1417
image: wangsiye/longhorn-ui:0bc7973
> fix(Dockerfile) Reduce image size

- package.json
- src/assets/styles/antd-customize/generic.less
- src/assets/styles/antd-customize/tree.less
- src/components/Snapshot/Snapshot.js
- src/routes/app.js
- src/routes/backup/BackupList.js
- src/routes/dashboard/components/eventLogs.js
- src/routes/host/HostList.js
- src/routes/host/ReplicaList.js
- src/routes/setting/setting.js
- src/routes/volume/RecurringList.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/RecurringList.js
image:  wangsiye/longhorn-ui:cac7544
https://github.com/longhorn/longhorn/issues/1329
> Fix(antd) Upgrade antd verison 3.19.4 to 3.26.16

- src/routes/volume/detail/Snapshots.js
https://github.com/longhorn/longhorn/issues/1428
image:  wangsiye/longhorn-ui:cac7544
> fix(snapshot) Modify the position of the scroll bar in snapshots

- src/models/host.js
- src/routes/host/BulkEditNode.js
- src/routes/host/BulkEditNode.less
- src/routes/host/HostBulkActions.js
- src/routes/host/HostFilter.js
- src/routes/host/index.js
https://github.com/longhorn/longhorn/issues/1447
image: wangsiye/longhorn-ui:f2b8831
> feat(host) Support to edit multiple nodes

- src/models/host.js
- src/routes/host/BulkEditNode.js
- src/routes/host/HostBulkActions.js
- src/routes/host/components/EditableDiskItem.js
- src/routes/host/index.js
https://github.com/longhorn/longhorn/issues/1447
> fix(node) Fix the logic of node batch scheduling operation

- .eslintrc
- jest.config.js
- package.json
- src/utils/__tests__/sort.js
Signed-off-by: AnnatarHe <iamhele1994@gmail.com>
> feat(test): add unit test

- src/models/backup.js
- src/routes/backup/BulkCreateStandbyVolumeModal.js
- src/routes/backup/CreateStandbyVolume.js
- src/routes/backup/index.js
https://github.com/longhorn/longhorn/issues/1567
> feat(DR volume) Support node/disk tag selection for DR volume

- src/routes/backup/BackupDetail.js
https://github.com/longhorn/longhorn/issues/1571
> fix(DR volume) Fix detail backup page create DRvolume

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/1561
image: wangsiye/longhorn-ui:5008222
> fix(Delete message) Optimized the prompt message for deleting volume

- src/routes/volume/VolumeList.js
image: wangsiye/longhorn-ui:0827dca
https://github.com/longhorn/longhorn/issues/1598
> Fix(volume style) Fix the style error of volume name in Firefox

- src/models/backup.js
- src/publicPath.js
- webpack.config.production.js
image: wangsiye/longhorn-ui:c887282
https://github.com/longhorn/longhorn/issues/1643
> fix(build) Change absolute path to relative path

- .drone.yml
Signed-off-by: Sheng Yang <sheng.yang@rancher.com>
> Update drone to v1.0.x

- nginx.conf.template
- src/components/Layout/Bread.js
- src/components/Layout/BundlesModel.js
- src/components/Layout/Menu.js
- src/components/LinkTo/LinkTo.js
- src/components/Snapshot/Snapshot.js
- src/index.js
- src/main.js
- src/models/app.js
- src/models/backup.js
- src/models/volume.js
- src/publicPath.js
- src/router.js
- src/routes/backup/BackupVolumeList.js
- src/routes/backup/index.js
- src/routes/dashboard/components/numberCard.js
- src/routes/dashboard/index.js
- src/routes/engineimage/EngineImageList.js
- src/routes/engineimage/index.js
- src/routes/host/ReplicaList.js
- src/routes/host/index.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/index.js
- src/routes/volume/index.js
- src/utils/backup.js
- src/utils/pathnamePrefix.js
- src/utils/request.js
- src/utils/websocket.js
image: wangsiye/longhorn-ui:239637e
https://github.com/longhorn/longhorn/issues/1660
>  feat(router) Modify the route to HashHistory mode

- src/models/app.js
image: wangsiye/longhorn-ui:59b250e
> fix(Support Bundle) Fix the download link address

- Dockerfile
image: wangsiye/longhorn-ui:0745090
> fix(image) Upgrade image

- src/routes/host/ReplicaList.js
- src/routes/host/index.js
https://github.com/longhorn/longhorn/issues/1697
image: wangsiye/longhorn-ui:6f98076
> fix(replica) Fix the logic of replicas link passing params

- src/components/Snapshot/Snapshot.js
- src/routes/volume/RecurringBulkList.js
- src/routes/volume/RecurringList.js
- src/routes/volume/SnapshotBulkModal.js
- src/routes/volume/SnapshotDetailModal.js
- src/routes/volume/detail/RecurringList.js
- src/routes/volume/detail/Snapshots.js
https://github.com/longhorn/longhorn/issues/1686
image: wangsiye/longhorn-ui:9b91ce8
> feat(Snapshots) Show cron job name

- src/components/Replica/Replica.js
https://github.com/longhorn/longhorn/issues/1279
> fix(progress) Fix the color of the progress bar

- src/models/volume.js
- src/routes/volume/UpdateBulkReplicaCount.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/1715
image: wangsiye/longhorn-ui:a8a06fd
> feat(replica) Support batch editing replica

- src/models/volume.js
- src/publicPath.js
- src/routes/volume/CustomColumn.js
- src/routes/volume/CustomColumn.less
- src/routes/volume/VolumeList.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/1716
image: wangsiye/longhorn-ui:59267b9
> feat(custom columns) Support custom columns

- src/routes/setting/setting.js
https://github.com/longhorn/longhorn/issues/1743
image: wangsiye/longhorn-ui:59267b9
> fix(settings) Support dynamic loading of setting items

- src/components/Layout/Bread.js
- src/routes/backup/BackupList.js
- src/routes/setting/setting.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
image: wangsiye/longhorn-ui:401ea4f
https://github.com/longhorn/longhorn/issues/1753
> Fix some known bugs

- src/models/host.js
- src/routes/host/BulkEditNode.js
- src/routes/host/EditDisk.js
- src/routes/host/components/EditableDiskItem.js
- src/routes/host/components/EditableDiskList.js
- src/routes/host/index.js
- src/routes/volume/VolumeList.js
https://github.com/longhorn/longhorn/issues/298
image: wangsiye/longhorn-ui:c3b7da7
> feat(node) Add eviction operation

- src/routes/volume/UpdateBulkReplicaCount.js
https://github.com/longhorn/longhorn/issues/1715
image: wangsiye/longhorn-ui:c3b7da7
> fix(replica) Fix initialization replicaCount value type error

- src/models/volume.js
- src/routes/volume/CreateVolume.js
- src/routes/volume/UpdateBulkDataLocality.js
- src/routes/volume/UpdateDataLocality.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/1744
image: wangsiye/longhorn-ui:c3b7da7
> feat(volume) Support Data Locality

- src/assets/styles/antd-customize/tree.less
- src/components/Snapshot/Snapshot.js
https://github.com/longhorn/longhorn/issues/1762
> fix(snapshot) Fix the problem of overlapping drop-down menus

- src/routes/host/BulkEditNode.js
https://github.com/longhorn/longhorn/issues/1776
> fix(node) Fix the Node scheduling options

- .drone.yml
> Add drone build for ARM64 support

- src/routes/volume/detail/Snapshots.js
https://github.com/longhorn/longhorn/issues/1878
image: wangsiye/longhorn-ui:a53da78
> Fix(snapshot) Fix system hidden button apsolute position

- .drone.yml
> add drone slack notifications

- src/routes/setting/setting.js
https://github.com/longhorn/longhorn/issues/1889
image: wangsiye/lognhorn-ui:d589128
> fix(settings) Fix bug with setings page sorting error

- Dockerfile
image: wangsiye/lognhorn-ui:d589128
> fix(nginx) Upgrade nginx version

- src/routes/host/HostActions.js
- src/routes/host/HostBulkActions.js
- src/routes/host/HostFilter.js
- src/routes/host/HostList.js
- src/routes/host/index.js
image: wangsiye/longhorn-ui:2da8e81
https://github.com/longhorn/longhorn/issues/1901
> fix(node) Clear operations that delete node

- src/components/Snapshot/Snapshot.js
https://github.com/longhorn/longhorn/issues/1780
image: wangsiye/longhorn-ui:c4e4858
> fix(snapshot) Fix options doesn't scroll with the screen

- src/components/Replica/Replica.js
image: wangsiye/longhorn-ui:1f6dca1
https://github.com/longhorn/longhorn/issues/1994
> fix(volume) Fix diskpath display error in volume details page.

- src/models/host.js
- src/routes/host/DiskList.js
- src/routes/host/index.js
image: wangsiye/longhorn-ui:1f6dca1
https://github.com/longhorn/longhorn/issues/1995
> fix(replicas) Fix the bug that disks replicas list is empty

- src/routes/backup/BackupDetail.js
- src/routes/backup/BulkCreateStandbyVolumeModal.js
- src/routes/backup/CreateStandbyVolume.js
- src/routes/backup/RestoreBackup.js
- src/routes/volume/CreateVolume.js
https://github.com/longhorn/longhorn/issues/2048
> feat(accessMode) Add an accessMode option for create volume

- src/routes/volume/CustomColumn.js
- src/routes/volume/VolumeList.js
https://github.com/longhorn/longhorn/issues/2040
image: wangsiye/longhorn-ui:a796d3c
> Add replicas and dataLocality fields to custom column

- src/routes/volume/CreateVolume.js
https://github.com/longhorn/longhorn/issues/2025
> fix(volume) Add verification for creating a volume

- src/models/volume.js
- src/routes/volume/CreatePVAndPVC.js
- src/routes/volume/CreatePVAndPVCSingle.js
- src/routes/volume/UpdateAccessMode.js
- src/routes/volume/UpdateBulkAccessMode.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/2048
> feat(Access Mode) Add option to update Access Mode

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/2094
image: wangsiye/longhorn-ui:743c52c
> fix(pvc) Disable update access mode when volume is bound to pv or pvc

- Makefile
https://github.com/longhorn/longhorn/issues/2091
> update base image to get the latest changes before build

- nginx.conf.template
Reverts longhorn/longhorn-ui#320
Due to https://github.com/longhorn/longhorn/issues/2136
> Revert "Make nginx listen on IPv6 too"

- src/components/DropOption/DropOption.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/2059
image:  wangsiye/longhorn-ui:03ed7dc
> fix(volume) Add detach tooltip message for RWX volume

- src/publicPath.js
- src/routes/backup/BackupList.js
- src/routes/backup/BackupVolumeList.js
- src/routes/host/HostList.js
- src/routes/volume/VolumeList.js
- src/utils/page.js
https://github.com/longhorn/longhorn/issues/2142
wangsiye/longhorn-ui:7e36922
> feat(settings) Support to modify table rows per page

- src/routes/volume/VolumeList.js
- src/utils/sort.js
https://github.com/longhorn/longhorn/issues/2193
> fix(volume) Fix volume page sorting bug

- src/routes/volume/EngineUpgrade.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/index.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/2205
> feat(engine) Disable update when set to automatically upgrade the engine

- src/routes/host/HostList.js
- src/routes/volume/VolumeList.js
- src/utils/sort.js
https://github.com/longhorn/longhorn/issues/2247
> Fix the bug in node list sorting error

- Dockerfile
> Upgrade the nginx image to 1.19.6-alpine

- src/routes/setting/setting.js
https://github.com/longhorn/longhorn/issues/2253
> fix(settings) Add integer validation to settings configuration items

- src/routes/host/HostActions.js
- src/routes/host/HostBulkActions.js
- src/routes/host/HostFilter.js
- src/routes/host/HostList.js
- src/routes/host/index.js
Add back the node deletion from https://github.com/longhorn/longhorn-ui/commit/bb53c5ff352166ed58c7ae2e0d4baf4ada3cab82.
https://github.com/longhorn/longhorn/issues/2186
> Add node deletion

- src/components/Layout/Bread.js
- src/components/Layout/Footer.js
- src/index.js
- src/models/backingImage.js
- src/models/backup.js
- src/router.js
- src/routes/backingImage/BackingImageActions.js
- src/routes/backingImage/BackingImageList.js
- src/routes/backingImage/CreateBackingImage.js
- src/routes/backingImage/DiskStateMapActions.js
- src/routes/backingImage/DiskStateMapDetail.js
- src/routes/backingImage/index.js
- src/routes/backup/BackupDetail.js
- src/routes/backup/BackupVolumeList.js
- src/routes/backup/BulkCreateStandbyVolumeModal.js
- src/routes/backup/CreateStandbyVolume.js
- src/routes/backup/RestoreBackup.js
- src/routes/backup/index.js
- src/routes/engineimage/index.js
- src/routes/volume/CreateVolume.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/index.js
- src/services/backingImage.js
- src/utils/index.js
- src/utils/menu.js
https://github.com/longhorn/longhorn/issues/2006
> Support raw or qcow2 file as the backing image

- src/routes/volume/VolumeList.js
- src/utils/status.js
https://github.com/longhorn/longhorn/issues/2281
> fix(upgrad engine) Prompt message when upgrading engine automatically

- src/assets/styles/antd-customize/generic.less
- src/routes/host/EditDisk.js
- src/routes/host/components/EditableDiskList.js
- src/routes/setting/setting.js
https://github.com/longhorn/longhorn/issues/2207
> feat(node) Support to modify node cpu reservation

- src/assets/styles/classes.less
- src/routes/engineimage/detail/EngineImageInfo.js
- src/routes/engineimage/detail/EngineImageInfo.less
- src/routes/engineimage/detail/index.js
- src/routes/volume/EngineUpgrade.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/2311
> Change engine image state from ready to deployed

- src/components/Layout/Footer.js
https://github.com/longhorn/longhorn/issues/2373
> fix(footer) Change the link address for creating an issue

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/2338
> fix the conditions for rwx volume to perform detach operation

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
> fix(action) fix the conditions of the volume expand action

- src/routes/host/HostActions.js
- src/routes/host/HostList.js
- src/routes/host/index.js
https://github.com/longhorn/longhorn/issues/2308
wangsiye/longhorn-ui:6b7d26f
> fix(node) Remove 'Enable Scheduling' options for 'down' node

- src/components/Layout/Bread.js
https://github.com/longhorn/longhorn/issues/2424
> fix(bread) Fix bread nav the wrong case bug

- src/routes/host/components/InstanceManagerComponent.js
https://github.com/longhorn/longhorn/issues/2377
> fix(node) Fix the status of engineimage on node

- src/models/backingImage.js
- src/models/engineimage.js
- src/models/eventlog.js
- src/models/host.js
- src/models/setting.js
- src/models/volume.js
- src/routes/engineimage/index.js
- src/utils/websocket.js
https://github.com/longhorn/longhorn/issues/2372
image: wangsiye/longhorn-ui:1ecd4e5
> fix(ws) Optimising websocket data

- src/utils/websocket.js
https://github.com/longhorn/longhorn/issues/2372
> fix(ws) Stop updating data when resourceType is undefined

- Dockerfile
> fix(nginx) update nginx to 1.19.9-alpine

- src/routes/backingImage/DiskStateMapDetail.js
- src/routes/backingImage/index.js
https://github.com/longhorn/longhorn/issues/2295
> feat(backing image) Add download progress for backing image

- src/routes/volume/AttachHost.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/helper/index.js
https://github.com/longhorn/longhorn/issues/2411
> fix(volume) fix the conditions for volume attach and detach operations

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/helper/index.js
https://github.com/longhorn/longhorn/issues/2411
> fix(code) Optimize detach action code

- src/routes/host/HostActions.js
https://github.com/longhorn/longhorn/issues/2462
> fix(node) Add warning message when deleting node

- src/routes/backingImage/BackingImageList.js
- src/routes/backingImage/CreateBackingImage.js
- src/routes/backingImage/DiskStateMapDetail.js
https://github.com/longhorn/longhorn/issues/2494
> fix(backingImage) URL typo error

- src/routes/backingImage/BackingImageList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
https://github.com/longhorn/longhorn/issues/2497
> fix(backing) Show the backing image size

- src/routes/backingImage/DiskStateMapActions.js
- src/routes/backingImage/DiskStateMapDetail.js
https://github.com/longhorn/longhorn/issues/2506
image: wangsiye/longhorn-ui:f12341d
> fix(backing Image) Modify delete prompt

- src/routes/backingImage/DiskStateMapActions.js
- src/routes/backingImage/DiskStateMapDetail.js
https://github.com/longhorn/longhorn/issues/2506
> fix(backing image) Modify delete prompt message 'images' to 'image file'

- src/routes/backingImage/CreateBackingImage.js
image: wangsiye/longhorn-ui:d568cc3
https://github.com/longhorn/longhorn/issues/2516
> fix(backingImage) Modify the size of the backingImage pop-up

- src/routes/volume/detail/EventList.js
image: wangsiye/longhorn-ui:fed6856
https://github.com/longhorn/longhorn/issues/2567
> fix(volume) Fix the minwidth of the name column in the event log table

- src/models/volume.js
https://github.com/longhorn/longhorn/issues/2595
image: wangsiye/longhorn-ui:f406625
> fix(volume) Clear selection after creating backup

- src/models/volume.js
- src/routes/volume/detail/index.js
https://github.com/longhorn/longhorn/issues/2587
> fix(detach) Fix the detach operation in volume details page

- Dockerfile
fix CVE-2021-30139
https://github.com/longhorn/longhorn/issues/2622
> upgrade nginx base image version

- package.json
- src/models/app.js
- src/models/backingImage.js
- src/models/engineimage.js
- src/models/eventlog.js
- src/models/host.js
- src/models/setting.js
- src/models/volume.js
- src/routes/dashboard/index.js
- src/routes/volume/detail/EventList.js
- src/routes/volume/detail/index.js
- src/utils/dataDependency.js
- src/utils/websocket.js
- webpack.config.development.js
image: wangsiye/longhorn-ui:9741071
https://github.com/longhorn/longhorn/issues/2593
> feat(ws) Close WS if data not used on page

- src/models/backup.js
https://github.com/longhorn/longhorn/issues/2652
> fix(backup) Clear the selected after performing the requested operation

- src/routes/volume/ExpansionVolumeSizeModal.js
https://github.com/longhorn/longhorn/issues/2422
> fix(volume) Remove the tips for pv/pvc in the extended volume modal

- src/assets/styles/antd-customize/generic.less
- src/routes/volume/RecurringBulkList.js
- src/routes/volume/SnapshotBulkModal.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/2691
>  fix(volume) Optimisation of data-less hints for cron job table

- src/assets/styles/antd-customize/generic.less
- src/routes/volume/RecurringBulkList.js
- src/routes/volume/SnapshotBulkModal.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/2691
> fix(volume) Optimisation of data-less hints for cron job table

- src/models/volume.js
- src/routes/volume/CreateVolume.js
- src/routes/volume/UpdateReplicaAutoBalanceModal.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/2676
> feat(volume) Implement Replica Auto Balance Settings

- Dockerfile
https://github.com/longhorn/longhorn/issues/2734
> [v1.1.2-backport] update base image

- Dockerfile
https://github.com/longhorn/longhorn/issues/2734
> [v1.1.1] update base image

- package.json
> [WIP] fix(axios) Upgrade axios to v0.21.1

- package.json
> fix(axios) Upgrade axios to v0.21.1

- src/models/backup.js
https://github.com/longhorn/longhorn/issues/2754
> fix(backup) Fix the backup details page data becomes empty after request

- .gitignore
- Dockerfile
ref: https://ci.longhorn.io/job/private/job/image-security-scan/355/
Signed-off-by: David Ko <dko@suse.com>
> Frequently update installed packages of image

- src/components/Snapshot/Snapshot.js
- src/routes/backup/BackupList.js
- src/routes/backup/BackupVolumeList.js
- src/routes/backup/ShowBackupLabels.js
- src/routes/backup/backupList.less
- src/routes/engineimage/EngineImageList.js
- src/routes/engineimage/detail/EngineImageInfo.js
- src/routes/host/components/EditableDiskItem.js
- src/routes/host/components/EditableDiskList.js
- src/routes/volume/Salvage.js
- src/routes/volume/VolumeList.js
- src/routes/volume/VolumeList.less
- src/routes/volume/WorkloadDetailModal.js
- src/routes/volume/detail/EventList.js
- src/routes/volume/detail/SnapshotList.js
- src/routes/volume/detail/VolumeInfo.js
- src/utils/formatDate.js
In order to ensure the uniformity of the date format, most of the timestamps that can be added to the tooltip have been modified.
image: wangsiye/longhorn-ui:72f59d6
https://github.com/longhorn/longhorn/issues/2808
> feat(date) Add tooltip for dates to show YYYY-MM-DD h:mm:ss format dates

- src/models/backup.js
- src/models/volume.js
- src/routes/backup/RestoreBackup.js
- src/routes/volume/CreatePVAndPVCSingle.js
- src/routes/volume/CreateVolume.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
- src/routes/volume/index.js
image: wangsiye/longhorn-ui:e68aeb2
https://github.com/longhorn/longhorn/issues/2841
> feat(volume) UI add volume encryption support

- .gitignore
- src/assets/styles/antd-customize/generic.less
- src/models/backingImage.js
- src/models/backup.js
- src/routes/backingImage/BackingImage.less
- src/routes/backingImage/BackingImageActions.js
- src/routes/backingImage/BackingImageBulkActions.js
- src/routes/backingImage/BackingImageList.js
- src/routes/backingImage/CreateBackingImage.js
- src/routes/backingImage/DiskStateMapDetail.js
- src/routes/backingImage/index.js
- src/routes/backup/BackupDetail.js
- src/routes/backup/CreateStandbyVolume.js
- src/routes/backup/RestoreBackup.js
- src/routes/backup/index.js
> feat(backingImage) BackingImage page refactor

- nginx.conf.template
- src/models/app.js
- src/models/backingImage.js
- src/routes/backingImage/BackingImage.less
- src/routes/backingImage/CreateBackingImage.js
- src/routes/backingImage/DiskStateMapDetail.js
- src/routes/backingImage/index.js
- src/services/backingImage.js
https://github.com/longhorn/longhorn/issues/2404
image: wangsiye/longhorn-ui:aa75768
> feat(backing image) Support upload large backing image file

- src/routes/backingImage/DiskStateMapDetail.js
https://github.com/longhorn/longhorn/issues/2404
image: wangsiye/longhorn-ui:1b04175
> fix(backingImage) Does not show summary when upload fails.

- src/routes/backup/CreateStandbyVolume.js
- src/routes/volume/VolumeList.js
image: wangsiye/longhorn-ui:2e0bf47
https://github.com/longhorn/longhorn/issues/2841
> feat(encrypted)DR volume support encrypted.

- src/models/backup.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/detail/Snapshots.js
- src/routes/volume/detail/index.js
- src/routes/volume/index.js
- src/services/backup.js
https://github.com/longhorn/longhorn/issues/2887
> feat(backup target) Support for backup target new api interface

- src/routes/backup/BackupList.js
https://github.com/longhorn/longhorn/issues/2916
> fix(backup) Add Creation State column to the backup list

- src/components/AutoComplete/AutoComplete.js
- src/components/index.js
- src/routes/backingImage/CreateBackingImage.js
- src/routes/backingImage/DiskStateMapDetail.js
- src/routes/backingImage/index.js
- src/utils/dataDependency.js
https://github.com/longhorn/longhorn/issues/2403
> feat(backingImage) Backingimage support export from volume

- src/routes/backup/BackupDetail.js
- src/routes/backup/BackupList.js
https://github.com/longhorn/longhorn/issues/2912
> fix(delete backup) Fixes the parameters for passing volumeName

- src/models/backup.js
https://github.com/longhorn/longhorn/issues/2944
image: wangsiye/longhorn-ui:eb498e0
> fix(backup) Clear the error message when backup target is available

- src/routes/backup/BackupList.js
https://github.com/longhorn/longhorn/issues/3023
> feat(backup) Show loading icon when backup is being created

- src/components/Snapshot/Snapshot.js
- src/routes/backup/BackupList.js
- src/routes/backup/BackupVolumeList.js
- src/routes/backup/ShowBackupLabels.js
- src/routes/engineimage/EngineImageList.js
- src/routes/engineimage/detail/EngineImageInfo.js
- src/routes/volume/Salvage.js
- src/routes/volume/VolumeList.js
- src/routes/volume/WorkloadDetailModal.js
- src/routes/volume/detail/VolumeInfo.js
- src/utils/formatDate.js
https://github.com/longhorn/longhorn/issues/2994
> fix(time) Convert time format to UTC

- src/components/Layout/Footer.js
- src/components/Layout/StableLonghornVersions.js
- src/models/app.js
https://github.com/longhorn/longhorn/issues/3032
image: wangsiye/longhorn-ui:f696a77
> feat(footer) Add Stable Longhorn Versions information display

- src/components/Layout/Footer.js
- src/components/Layout/StableLonghornVersions.js
- src/models/app.js
https://github.com/longhorn/longhorn/issues/3032
> feat(footer) Add newer stable Versions information display

- src/routes/volume/detail/index.js
- src/routes/volume/index.js
image: wangsiye/longhorn-ui:f8a1f4e
https://github.com/longhorn/longhorn/issues/3217
> fix(expand volume) Change the default unit to Gi

- src/routes/backup/BackupList.js
image:wangsiye/longhorn-ui:7784506
https://github.com/longhorn/longhorn/issues/3168
> feat(backup) The backup list supports progress

- src/routes/backup/BackupList.js
Reverts longhorn/longhorn-ui#459
> Revert "feat(backup) The backup list supports progress"

- src/utils/formatDate.js
https://github.com/longhorn/longhorn/issues/3230
> fix(date) Eliminate browser's console warning message

- src/routes/recurringJob/CreateRecurringJob.js
- src/routes/recurringJob/index.js
https://github.com/longhorn/longhorn/issues/3180
image: wangsiye/longhorn-ui:429beb9
> fix(cron) Pass the default value of the current recurringJob's cron

- Dockerfile
longhorn/longhorn#2842
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
> backport base image updates

- src/routes/setting/setting.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/3308
> fix(setting) Fix revision counter setting typo error

- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/3308
> fix(typo) fix revision counter label

- src/components/Snapshot/Snapshot.js
https://github.com/longhorn/longhorn/issues/3394
> fix(snapshot) Show snapshot in different color when backup fails

- src/components/Snapshot/Snapshot.js
- src/routes/volume/detail/SnapshotList.js
- src/utils/formater.js
https://github.com/longhorn/longhorn/issues/3228
> fix(backup) Display the actual backup size on the volume detail page

- src/assets/styles/classes.less
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/3291
> fix(volume) Fix volume list state when volume.robustness is unknown

- src/assets/styles/antd-customize/generic.less
- src/index.js
- src/models/backingImage.js
- src/models/backup.js
- src/models/dashboard.js
- src/models/engineimage.js
- src/models/eventlog.js
- src/models/host.js
- src/models/instanceManager.js
- src/models/setting.js
- src/models/volume.js
- src/publicPath.js
- src/router.js
- src/routes/backingImage/BackingImageList.js
- src/routes/backup/BackupList.js
- src/routes/host/HostList.js
- src/routes/instanceManager/InstanceManagerList.js
- src/routes/instanceManager/RefCountVolumeModal.js
- src/routes/instanceManager/index.js
- src/routes/volume/VolumeList.js
- src/routes/volume/index.js
- src/services/instanceManager.js
- src/utils/dataDependency.js
- src/utils/menu.js
https://github.com/longhorn/longhorn/issues/3306
https://github.com/longhorn/longhorn/issues/3528
> Support instance manager image and Loading http requests on demand

- src/utils/dataDependency.js
https://github.com/longhorn/longhorn/issues/3528
> fix(http) fix backup target dependency for volume

- src/routes/backup/BackupVolumeList.js
https://github.com/longhorn/longhorn/issues/3676
image: wangsiye/longhorn-ui:a18d18e
> [v1.2.x] fix(css) Fix backup volume table style error

- src/assets/styles/antd-customize/generic.less
- src/routes/backingImage/BackingImageList.js
- src/routes/backup/BackupVolumeList.js
https://github.com/longhorn/longhorn/issues/3676
image: wangsiye/longhorn-ui:45792d9
> [v1.1.x] fix(css) Fix backup volume table style error

- src/routes/recurringJob/RecurringJobActions.js
- src/routes/recurringJob/RecurringJobBulkActions.js
https://github.com/longhorn/longhorn/issues/3651
> [master] feat(recurring job) Show warning message when deleting a recurring job

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
image: wangsiye/longhorn-ui:54b0421 (v1.2.x)
https://github.com/longhorn/longhorn/issues/3807
> fix(PV/PVC) Disable PV/PVC creation while volume is being created

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/3807
> [master] fix(PV/PVC) Disable PV/PVC creation while volume is being created

- Dockerfile
- nginx.conf.template
https://github.com/longhorn/longhorn/issues/3829
> [master] feat(nginx) Make Longhorn UI Listen Binding configurable

- package.json
> [master] fix(CVE) Fix CVE-2022-24785

- package.json
> fix(CVE) Fix CVE-2022-24785

- src/routes/backup/BackupVolumeList.js
https://github.com/longhorn/longhorn/issues/3676
> [master] fix(css) Fix backup volume table style error

- Dockerfile
- Makefile
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
Ref: https://github.com/longhorn/longhorn/issues/2939
> change base image to SUSE BCI

- .drone.yml
- Dockerfile
This PR adds support to build on s390x architecture.
> Add s390x support

- src/index.js
- src/models/orphanedData.js
- src/publicPath.js
- src/router.js
- src/routes/orphanedData/index.js
- src/routes/orphanedData/orphanedDataActions.js
- src/routes/orphanedData/orphanedDataBulkActions.js
- src/routes/orphanedData/orphanedDataList.js
- src/services/orphanedData.js
- src/utils/dataDependency.js
- src/utils/menu.js
https://github.com/longhorn/longhorn/issues/3826
image: wangsiye/longhorn-ui:3134d8b
> feat(orphaned) Add orphaned data page

- src/models/backingImage.js
- src/models/engineimage.js
- src/models/eventlog.js
- src/models/host.js
- src/models/recurringJob.js
- src/models/setting.js
- src/models/volume.js
https://github.com/longhorn/longhorn/issues/3935
image: wangsiye/longhorn-ui:a441f8c
> [v1.2.x] fix(ws) Fix the bug that the ws icon is displayed incorrectly

- src/models/backingImage.js
- src/models/engineimage.js
- src/models/eventlog.js
- src/models/host.js
- src/models/recurringJob.js
- src/models/setting.js
- src/models/volume.js
https://github.com/longhorn/longhorn/issues/3935
image: wangsiye/longhorn-ui:a441f8c
> [master] fix(ws) Fix the bug that the ws icon is displayed incorrectly

- src/models/backingImage.js
- src/routes/backingImage/BackingImageActions.js
- src/routes/backingImage/BackingImageList.js
- src/routes/backingImage/index.js
- src/services/backingImage.js
image: wangsiye/longhorn-ui:399b94e
https://github.com/longhorn/longhorn/issues/3155
> feat(backing-image) Support download backing image

- src/routes/backingImage/BackingImageList.js
image: wangsiye/longhorn-ui:4401b00
https://github.com/longhorn/longhorn/issues/4052
> feat(backing image) Add a UUID column to the backing image list

- src/routes/volume/VolumeList.js
image: wangsiye/longhorn-ui:0e1ba41
> feat(Expand volume) Add tooltip message on failure of volume expansion

- src/routes/volume/VolumeList.js
https://github.com/longhorn/longhorn/issues/4475
> [v1.3.x] feat(Expand volume) Add tooltip message on failure of volume expansion

- src/routes/volume/VolumeList.js
https://github.com/longhorn/longhorn/issues/4475
> [1.2.x] feat(Expand volume) Add tooltip message on failure of volume expansion

- src/components/Replica/Replica.js
https://github.com/longhorn/longhorn/issues/4430
> [master] fix(replica) Fix confusing description

- src/components/Replica/Replica.js
https://github.com/longhorn/longhorn/issues/4430
>  [1.2.x] fix(replica) Fix confusing description

- src/components/Replica/Replica.js
https://github.com/longhorn/longhorn/issues/4430
> [1.3.x] fix(replica) Fix confusing description

- src/utils/filter.js
One of my longhorn nodes is not currently schedulable due to kubernetes nonsense, and this has broken the whole UI as it throws an exception on page load due to one node being bad. Also a little formatting as those one-liners are getting out of control.
> Check if node schedulable condition is set before trying to read it

- src/utils/filter.js
[Issue #4582](https://github.com/longhorn/longhorn/issues/4582)
Signed-off-by: Ray Chang <ray.chang@suse.com>
Backport for [Issue #4581](https://github.com/longhorn/longhorn/issues/4581)
> [BACKPORT][v1.3.x] Check if node schedulable condition is set before trying to read it

- src/utils/filter.js
[Issue #4583](https://github.com/longhorn/longhorn/issues/4583)
Signed-off-by: Ray Chang <ray.chang@suse.com>
Backport for [Issue #4581](https://github.com/longhorn/longhorn/issues/4581)
> [BACKPORT][v1.2.x] Check if node schedulable condition is set before trying to read it

- nginx.conf.template
https://github.com/longhorn/longhorn/issues/4902
> [WIP] fix(upload file) Remove the nginx client_max_body_size limit

- nginx.conf.template
https://github.com/longhorn/longhorn/issues/4902
> [1.2.x] fix(upload file) Remove the nginx client_max_body_size limit

- nginx.conf.template
https://github.com/longhorn/longhorn/issues/4902
> [v1.3.x] fix(upload file) Remove the nginx client_max_body_size limit

- src/models/volume.js
- src/routes/volume/CreateVolume.js
- src/routes/volume/UpdateBulkUnmapMarkSnapChainRemovedModal.js
- src/routes/volume/UpdateUnmapMarkSnapChainRemovedModal.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
wangsiye/longhorn-ui:20599d3
https://github.com/longhorn/longhorn/issues/836
> feat(trim file system) Support Remove Snapshots During Filesystem Trim

- src/components/Layout/Footer.js
- src/index.js
- src/models/systemBackups.js
- src/router.js
- src/routes/systemBackups/createSystemBackup.js
- src/routes/systemBackups/createSystemRestore.js
- src/routes/systemBackups/index.js
- src/routes/systemBackups/systemBackups.less
- src/routes/systemBackups/systemBackupsAction.js
- src/routes/systemBackups/systemBackupsBulkActions.js
- src/routes/systemBackups/systemBackupsBulkActions.less
- src/routes/systemBackups/systemBackupsList.js
- src/routes/systemBackups/systemRestoresAction.js
- src/routes/systemBackups/systemRestoresBulkActions.js
- src/routes/systemBackups/systemRestoresList.js
- src/services/systemBackups.js
- src/utils/dataDependency.js
- src/utils/formater.js
- src/utils/menu.js
- src/utils/page.js
- src/utils/websocket.js
https://github.com/longhorn/longhorn/issues/4855
> Feat(System backup) Support longhorn system backup/restore

- src/models/volume.js
- src/routes/volume/CreateVolume.js
- src/routes/volume/UpdateBulkSnapshotDataIntegrityModal.js
- src/routes/volume/UpdateSnapshotDataIntegrityModal.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/4994
> feat(volume) Add the update snapshot data integrity option

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
https://github.com/longhorn/longhorn/issues/1674
> fix(expand volume) Attached volume support expand option

- src/routes/backup/RestoreBackup.js
https://github.com/longhorn/longhorn/issues/5009
> feat(backup) Support restore Recurring Jobs

- src/utils/formatDate.js
https://github.com/longhorn/longhorn/issues/5047
> fix(date) Initial date return null

- src/utils/formatDate.js
https://github.com/longhorn/longhorn/issues/5047
> [1.4.x] fix(date) Initial date return null

- src/routes/backup/RestoreBackup.js
https://github.com/longhorn/longhorn/issues/5009
> [1.4.x] feat(backup) Support restore Recurring Jobs

- src/utils/formatDate.js
https://github.com/longhorn/longhorn/issues/5047
> [v1.3.x] fix(date) Initial date return null

- src/routes/systemBackups/systemRestoresAction.js
- src/routes/systemBackups/systemRestoresBulkActions.js
https://github.com/longhorn/longhorn/issues/5065
> fix(system restore) Add warning message when deleting the system restore

- src/routes/volume/CreateVolume.js
https://github.com/longhorn/longhorn/issues/5090
> fix(volume) Add advanced configurations for creating volume

- src/routes/volume/CreateVolume.js
https://github.com/longhorn/longhorn/issues/5090
> [Master] fix(volume) Add advanced configurations for creating volume

- src/routes/volume/CreateVolume.js
- src/routes/volume/UpdateBulkSnapshotDataIntegrityModal.js
- src/routes/volume/UpdateSnapshotDataIntegrityModal.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/5126
> [master] fix(volume) Set the Snapshot Data Integrity init value to ignored

- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/5127
> fix(volume) Fix the Snapshot trim wrong label

- src/routes/systemBackups/createSystemBackup.js
- src/routes/systemBackups/createSystemRestore.js
https://github.com/longhorn/longhorn/issues/5066
> fix(system backup) Trim the name filed when creating system backup

- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/5127
> fix(volume) Add tooltip for 'Allow snapshots removal during trim'

- src/routes/volume/UpdateReplicaAutoBalanceModal.js
https://github.com/longhorn/longhorn/issues/5154
> fix(volume) Fix the 'Update Replicas Auto Balance' options typo error

- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/1674
> fix(expand volume) Display an error message when expansion fails

- nginx.conf.template
https://github.com/longhorn/longhorn/issues/5438
> fix(nginx) Use X-Forwarded-Host instead of Host

- Dockerfile
- README.md
- package-lock.json
- Sync `package-lock.json`with `package.json` so that git does not constantly complain that the file has been modified after running `npm install`. This will allow the use of `npm ci` instead of `npm install`
- Use `npm ci` which install the NPM package dependencies AS specified. This is better for continuous integration.
- Update the README and Dockerfile
> Sync `package-lock.json` and use `npm ci`

- package.json
Let eslint do the fixes that it is complaining in `npm run lint`.
> Add `npm run fix`

- src/models/volume.js
- src/routes/volume/CreateVolume.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/components/SoftAntiAffinityModal.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/5358
image: wangsiye/longhorn-ui:737e083
> feat(volume) Add softAntiAffinity and zoneSoftAntiAffiny for volume

- src/routes/recurringJob/CreateRecurringJob.js
- src/routes/volume/detail/CreateRecurringJob.js
https://github.com/longhorn/longhorn/issues/5529
wangsiye/longhorn-ui:c917f9f.
> feat(recurring job) Add filesystem-trim type for recurring job

- src/models/volume.js
- src/routes/volume/CreatePVAndPVC.js
- src/routes/volume/CreatePVAndPVC.less
- src/routes/volume/CreatePVAndPVCSingle.js
- src/services/volume.js
https://github.com/longhorn/longhorn/issues/3506
>  feat(pvc) Add storage class name for pvc

- src/models/volume.js
- src/routes/volume/CreatePVAndPVC.js
- src/routes/volume/CreatePVAndPVCSingle.js
https://github.com/longhorn/longhorn/issues/3506
image: wangsiye/longhorn-ui:79b50f6
> fix(PV) Add storage class for PV

- src/models/host.js
- src/routes/host/EditDisk.js
- src/routes/host/components/EditableDiskList.js
- src/routes/host/components/InstanceManagerComponent.js
- src/routes/instanceManager/index.js
https://github.com/longhorn/longhorn/issues/5876
image: wangsiye/longhorn-ui:e6c2c53
> feat(instance manager) Support new aio typed instance managers

- src/routes/systemBackups/createSystemBackup.js
https://github.com/longhorn/longhorn/issues/6028
image: wangsiye/longhorn-ui:14d57b9
> feat(system-backup) Support volume backup policy

- src/publicPath.js
- src/routes/dashboard/components/resourceOverview.js
- src/routes/host/DiskList.js
- src/routes/host/components/EditableDiskItem.js
- src/routes/host/components/EditableDiskList.js
- src/routes/host/components/PathInput.js
- src/routes/volume/CreateVolume.js
- src/routes/volume/CustomColumn.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/5846
image: wangsiye/longhorn-ui:07f1d94
> feat(node) Support create block disk type

- src/models/volume.js
https://github.com/longhorn/longhorn/issues/6004
> fix(volume) Fix the bug of bluk attach request

- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/6128
image: wangsiye/longhorn-ui:7e7f4a0
> fix(spdk) Hide the  on the volume detail page

- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/6169
> fix(spdk) fix misleading offline rebuilding hint

- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/6461
> feat(volume) Add volume scheduling failure message

- src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/6167
image: wangsiye/longhorn-ui:477f0e7
> fix(volume) Add tooltip for volumes in maintenance mode

- .gitignore
- src/models/host.js
- src/routes/volume/EngineUpgrade.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/detail/Snapshots.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/helper/index.js
- src/utils/status.js
Fixes: https://github.com/longhorn/longhorn/issues/6685
Fixes: https://github.com/longhorn/longhorn/issues/6841
> Replace `spec.engineImage` field in volume, engine and replica CRDs with `spec.image`

- src/routes/engineimage/EngineImageActions.js
Fixes: https://github.com/longhorn/longhorn/issues/7029
> Disable `Delete` menu for default engine image

- src/routes/backingImage/BackingImageActions.js
- src/routes/engineimage/EngineImageActions.js
- src/routes/host/DiskActions.js
- src/routes/host/HostActions.js
- src/routes/orphanedData/orphanedDataActions.js
- src/routes/recurringJob/RecurringJobActions.js
- src/routes/systemBackups/systemBackupsAction.js
- src/routes/systemBackups/systemRestoresAction.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/detail/RecurringJobActions.js
Fixes: https://github.com/longhorn/longhorn/issues/7032
> The action menu handler should stop event propagation

- src/routes/backingImage/index.js
- src/routes/backup/BackupList.js
- src/routes/backup/BackupVolumeList.js
- src/routes/host/HostList.js
- src/routes/instanceManager/index.js
- src/routes/orphanedData/index.js
- src/routes/recurringJob/index.js
- src/routes/systemBackups/index.js
- src/routes/volume/index.js
Fixes: https://github.com/longhorn/longhorn/issues/7036
> All components handle window resizing events incorrectly

- src/routes/volume/CreateVolume.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/index.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
> Add ReplicaDiskSoftAntiAffinity setting

- .drone.yml
remove s390 arch during drone workers maintenance
Signed-off-by: Yang Chiu [yang.chiu@suse.com](mailto:yang.chiu@suse.com)
> remove s390 arch during drone workers maintenance

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/helper/index.js
Fix displaying volume scheduling conditions in volume list and volume details page.
ref: longhorn/longhorn#7241
> fix: display volume conditions

- src/publicPath.js
- src/routes/volume/CreateVolume.js
- src/routes/volume/CustomColumn.js
- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeBulkActions.js
- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/helper/index.js
> v2 volume: rename backendStoreDriver to dataEngine

- src/routes/volume/CreateVolume.js
- src/routes/volume/VolumeList.js
- src/routes/volume/index.js
https://github.com/longhorn/longhorn/issues/7505
> volume: validate volume creation according to the enabled data engines

- src/routes/volume/VolumeList.js
- src/routes/volume/detail/VolumeInfo.js
Longhorn/longhorn#5947
Longhorn/longhorn#7524
> v2 volume: display v2 volume actual size

- src/routes/volume/VolumeActions.js
- src/routes/volume/VolumeList.js
- src/utils/filter.js
Ref: https://github.com/longhorn/longhorn/issues/7445
- It will now disable the Upgrade Action
- It will remove the upgrade icon
> Disables Upgrade action & icon for V2 volumes

- src/routes/volume/CreateVolume.js
Ref: https://github.com/longhorn/longhorn/issues/7522
Removes `maxCount` field validation moving it to BE
> removes create vol fe validation

- Dockerfile
15.4 went EOSL at the end of 2023 according to Trivy
> Bump base image to 15.5

- .drone.yml
- Dockerfile
ref: longhorn/longhorn#8166
Signed-off-by: davidko <dko@suse.com>
> ci: rollback BCI image to 15.5

- src/components/Filter/Filter.js
- src/routes/backingImage/BackingImage.less
- src/routes/backingImage/index.js
- src/utils/filter.js
- Add colorful text to disk status 
- Add `UUID` / `Created From` filter items in backing image page 
https://github.com/longhorn/longhorn/issues/7293
Filter
Colorful disk status
> Add colorful text to disk status and add more fitler in backing image page 

- src/routes/setting/LeaveSettingsModal.js
- src/routes/setting/index.js
- src/routes/setting/setting.js
- src/routes/setting/setting.less
Cherry-pick below 4 commits from master to v1.6.x branch
- dc5ee33e8c7ce85b6dfd24fbb838728f921cfb1b
- 26fb6b49b21290aaaef20416080058e304450804
- 638c9186dee206698b86446029d0b17d8f82354b
- af06f3e5164f5c52fedeb71277ec7b8fa7bd7476
[[BACKPORT][v1.6.3][IMPROVEMENT] Saving Settings page changes](https://github.com/longhorn/longhorn/issues/8602)
https://github.com/longhorn/longhorn-ui/assets/5744158/927bec0e-ca1b-47a6-a897-5e4a0cc83c56
> Show modal to alert users the unsaved change in general settings page (backport #721)

- src/routes/setting/LeaveSettingsModal.js
- src/routes/setting/index.js
- src/routes/setting/setting.js
- src/routes/setting/setting.less
Cherry-pick below 4 commits from master to `v1.5.x` branch
- dc5ee33e8c7ce85b6dfd24fbb838728f921cfb1b
- 26fb6b49b21290aaaef20416080058e304450804
- 638c9186dee206698b86446029d0b17d8f82354b
- af06f3e5164f5c52fedeb71277ec7b8fa7bd7476
[[BACKPORT][v1.5.6][IMPROVEMENT] Saving Settings page changes](https://github.com/longhorn/longhorn/issues/8599)
https://github.com/longhorn/longhorn-ui/assets/5744158/21ee25c8-23d2-4112-9fb2-729c0a9a0adc
> Show modal to alert users the unsaved change in general settings page (backport #721) 

- src/components/Snapshot/Snapshot.less
- src/routes/volume/detail/ConditionTooltip.js
- src/routes/volume/detail/VolumeInfo.js
- src/routes/volume/detail/VolumeInfo.less
- Add green / red color to condition icon and text to make them more obvious
- Add `Suggestion : Try to delete unused snapshots to free up space if needed` in tooManySnapashots tooltip when status = true
- Extract the logic of ConditionTooltip to an independent file
https://github.com/longhorn/longhorn/issues/6560
I modified the [selectedVolume](https://github.com/a110605/longhorn-ui/blob/5fd3e8b911610d40ec416aeead6ad075ea866249/src/routes/volume/detail/VolumeInfo.js#L22) with mock data in frontend code to simulate below cases. Since it's hard to create 100+ snapshots in reality to trigger that condition.
```
const mockScheduled = {
lastProbeTime: '',
lastTransitionTime: '2024-05-20T05:53:07Z',
message: 'some error message',
reason: '',
status: 'True',
type: 'Scheduled',
}
const …
```
> Make tooManySnapashots condition text more obvious 

- .github/workflows/build.yml
https://github.com/longhorn/longhorn/issues/8039
> ci: only run push image for master branch

- Dockerfile
Issue longhorn/longhorn#8721
Integrate package updates into the image build process. This reduces noise from irrelevant vulnerabilities, making the report more focused for Longhorn.
`None`
`None`
> Build(image): always update package

- Dockerfile
> build: update base image to bci 15.6

- src/routes/volume/UpdateReplicaAutoBalanceModal.js
Lowercase Replicas Auto Balance options in UpdateReplicaAutoBalanceModal which follow the same character case in `Setting -> General`
https://github.com/longhorn/longhorn/issues/7530
> Lowercase Replicas Auto Balance options in UpdateReplicaAutoBalanceModal 

- src/models/backup.js
- src/routes/backup/BulkCreateStandbyVolumeModal.js
- src/routes/backup/BulkRestoreBackupModal.js
- src/routes/backup/index.js
- src/routes/recurringJob/CreateRecurringJob.js
Found a bug from previous implementation. Some changed value won't update to the config states. That user may restore or create wrong volume while using bulk action. (See below comment for root cause)
[[IMPROVEMENT] Restore Latest Backup should be applied with BackingImage name value](https://github.com/longhorn/longhorn/issues/7560)
Bulk action for restore latest backup
https://github.com/longhorn/longhorn-ui/assets/5744158/425025b4-d2a2-4129-8d8f-430d10afb44b
Bulk action for create DR volume
https://github.com/longhorn/longhorn-ui/assets/5744158/d4560f4d-6173-43ee-94e8-c049ed79d1a5
> fix the changed value using bulk action won't update the config states

- .eslintrc
- src/routes/recurringJob/CreateRecurringJob.js
- src/routes/volume/detail/CreateRecurringJob.js
- Add parameters field in create recurring job within volume detail page (only show for backup task)
- Fix missing parameters field when edit `backup-force-create` job
- Fix typo
https://github.com/longhorn/longhorn/issues/8291#issuecomment-2216470535
> Add parameters field in create recurring job within volume detail page

- src/components/ReactCron/ReactCron.js
- src/models/backup.js
- src/routes/backup/BackupDetail.js
- src/routes/backup/BulkRestoreBackupModal.js
- src/routes/backup/CreateStandbyVolumeModal.js
- src/routes/backup/RestoreBackupModal.js
- src/routes/backup/index.js
- src/routes/recurringJob/CreateRecurringJob.js
- src/routes/volume/detail/CreateRecurringJob.js
Backport all PRs from https://github.com/longhorn/longhorn/issues/7560 to. v1.6.x branch.
https://github.com/longhorn/longhorn/issues/8671
**Bulk Restore Latest Backup**
https://github.com/user-attachments/assets/f6b1e26a-37d8-4a3a-9c47-0f62204a182a
**Bulk Create DR volume**
https://github.com/user-attachments/assets/ba8dfec6-6e4d-4c82-84c2-b401159c36e0
> improve bulk restore latest backup and bulk create DR volume actions (backport #759, #737, #742)

- src/routes/volume/CreateVolume.js
Lowercase Replica Auto Balance options in create volume modal
https://github.com/longhorn/longhorn/issues/8786#issuecomment-2330592962
> fix: lowercase Replica Auto Balance options in create volume modal

- src/routes/volume/CreateVolume.js
- src/routes/volume/detail/index.js
- src/routes/volume/helper/index.js
- src/routes/volume/index.js
Backport https://github.com/longhorn/longhorn-ui/pull/789 to v1.6.x
> fix: lowercase options name in volume page (backport #789) 

- .github/workflows/build.yml
- Dockerfile
- Makefile
- scripts/package
Backport the following secure PRs to v1.8.x:
- #863 
- #875 
- #877
> feat(ci): Backport secure build to v1.8.x

- src/models/snapshot.js
fix: undefined error in filterRemoved()
https://github.com/longhorn/longhorn/issues/10529
> fix: undefined error in filterRemoved()

- src/models/orphanedData.js
- src/routes/orphanedData/InstanceOrphans.js
- src/routes/orphanedData/ReplicaDataOrphans.js
Filter the deleted data on the frontend
[[BUG] Deleted orphan data still renders on the page until page refresh #10803](https://github.com/longhorn/longhorn/issues/10803)
- Verify the issues have been resolved: 
https://github.com/longhorn/longhorn/issues/10760#issuecomment-2849754394
https://github.com/user-attachments/assets/b97bde9a-c656-40ff-b3b7-3030d8db6717
N/A
> fix: remove deleted orphaned data from list

- nginx.conf.template
Support IPv6.
longhorn/longhorn#2259
> feat(ipv6): add listen address family support

- Dockerfile
> chore(dockerfile): replace node:16.20 with node:16.20-alpine
