longhorn/longhorn-ui

.eslintignore, src/models/engineimage.js, src/models/host.js, src/models/setting.js, src/models/volume.js, src/utils/websocket.js
Issues:
* Inbound websocket changes cause user input to be erased. This is particularly annoying for modal popups which close/reopen, losing all state.
* roadhog dev server doesn't forward websockets (need layer 4 forwarding), workaround should be to ignore CORS and create sockets directly to LONGHORN_MANAGER_IP - currently hardcoded to 127.0.0.1
=> Consume websocket apis

src/routes/dashboard/components/resourceOverview.js, src/routes/host/HostList.js, src/routes/host/helper/index.js, src/routes/volume/detail/VolumeInfo.js
1.Due to user umount disk, reset node size to 0 instead of negative value
2.Rounding the storage value in edit disk modal, due to Gi to byte may appear as decimals 
3.volume create time show invalid date in volume detail page non-chrome browser
4.reset schedulabe value to 0 if schedulable space is negative number in dashboard page
=> handling storage value in node page

src/components/Layout/Footer.js
**NOTE**: do not merge until the new Longhorn docs interface is done.
For now, the https://longhorn.io/docs URL is broken, but once the new Longhorn website is done, the Longhorn docs will be hosted "in house" and that link will go to the rendered Longhorn docs.
You can see a preview here: https://deploy-preview-16--longhornio.netlify.com/docs/.
=> Update docs URL

nginx.conf.template
Related to: https://github.com/longhorn/longhorn-manager/pull/663
The longhorn-ui nginx's server does not explicitely listen on IPv6. Because of this the longhorn-driver-deployer never becomes available and nothing works.
Cheers
=> Make nginx listen on IPv6 too

src/routes/host/HostList.js
When a node is down, change its Readiness status to NotReady.
https://github.com/longhorn/longhorn/issues/2186#issuecomment-765040722 - 2.
=> Fix readiness status when node is down

src/routes/engineimage/detail/index.js
Symptom:
Was:`Enging Image Detail`
Is: `Engine Image Detail`
=> Fix typo, it should be Engine

src/models/volume.js, src/routes/volume/VolumeList.js, src/routes/volume/detail/RecurringJob.js
https://github.com/longhorn/longhorn/issues/2996
1. Disable the add button when the volume has no actions associated with the recurringjob
2. Does not determine if the volume has been bound to a recurring job only displays the icon
=> fix (recurringJob)

src/models/volume.js, src/routes/volume/VolumeList.js, src/routes/volume/detail/RecurringJob.js
https://github.com/longhorn/longhorn/issues/2996
1. Disable the add button when the volume has no actions associated with the recurringjob
2. Does not determine if the volume has been bound to a recurring job only displays the icon
=> fix(recurringJob)

src/assets/styles/classes.less, src/routes/volume/VolumeList.js, src/routes/volume/detail/VolumeInfo.js
https://github.com/longhorn/longhorn/issues/3291
image: wangsiye/longhorn-ui:78c0fad
The pr mainly fixes the problem that the volume list and volume deatil page states are different when the volume state is attached and robustness is unkonw.
=> fix(volume) Fix volume list state when volume.robustness is unknown

src/assets/styles/antd-customize/generic.less, src/index.js, src/models/backingImage.js, src/models/backup.js, src/models/dashboard.js, src/models/engineimage.js, src/models/eventlog.js, src/models/host.js, src/models/instanceManager.js, src/models/recurringJob.js, src/models/setting.js, src/models/volume.js, src/publicPath.js, src/router.js, src/routes/backingImage/BackingImageList.js, src/routes/backup/BackupList.js, src/routes/host/HostList.js, src/routes/instanceManager/InstanceManagerList.js, src/routes/instanceManager/RefCountVolumeModal.js, src/routes/instanceManager/index.js, src/routes/recurringJob/RecurringJobList.js, src/routes/volume/VolumeList.js, src/routes/volume/index.js, src/services/instanceManager.js, src/utils/dataDependency.js, src/utils/menu.js
image: wangsiye/longhorn-ui:398a886
https://github.com/longhorn/longhorn/issues/3306
The pr implements two feature.
1. Load http requests on demand. The original longhorn-ui loads apis with all the data once every time the page is switched. This doesn't make much sense. It should load http requests on demand to reduce the pressure on the server.
2. Support the display of instance manager image list.
=> Support display instance manager image list

Dockerfile
This moves the NGINX config files to a tempfs because in a hardened environment root is a read-only system so we need to move it to an emptyDir that is mounted with fsGroup being set.
=> Moving to NGINX to tempfs

.drone.yml
Drone pipelines for s390x are failing due to the publish steps are not able to reach docker daemon
https://drone-publish.longhorn.io/longhorn/longhorn-ui/559/3/2
Adding the volume should do the trick.
Signed-off-by: Luis Tovar <luis.tovar@suse.coM>
=> Fix for not reaching docker daemon on s390x pipeline

src/routes/volume/Salvage.js
Fixes a typo in the Longhorn UI when salvaging a volume.
"Plase select at least one replica."
->
"Please select at least one replica."
Much better ;)
=> Typo fix: Plase select -> Please select

Dockerfile
Kubernete might check the UID exists in func `verifyRunAsNonRoot`
for `security_context` in rke2 enviroment.
longhorn/longhorn#4266
Signed-off-by: James Lu <james.lu@suse.com>
=> Run the UI container with user UID as a user

Dockerfile
Kubernete might check the UID exists in func `verifyRunAsNonRoot`
for `security_context` in rke2 enviroment.
longhorn/longhorn#4287
Signed-off-by: James Lu <jamesluhz@gmail.com>
=> [BARCKPORT][v1.3.x] Run the UI container with user UID as a user 

Dockerfile
Signed-off-by: David Ko <dko@suse.com>
=> ci(upstream): use node:16.16 to fix s390 missing from 16.17

Dockerfile
From SLE BCI 15.3 to 15.4 for security issue
ref: longhorn/longhorn#5107
=> build(image): bump the base image

src/routes/recurringJob/CreateRecurringJob.js, src/routes/volume/detail/CreateRecurringJob.js
Introduce new task types `snapshot-force-create` and `backup-force-create`. They can still take a new snapshot even if old snapshots cleanup failed.
Ref: longhorn/longhorn#4898, longhorn/longhorn#5610
=> feat(recurring-job): introduce two task types

README.md
This is necessary to fix/workaround this error:
```
Error: Command failed: /home/vot/git/longhorn-ui/node_modules/open/vendor/xdg-open "http://localhost:8080/"
/home/vot/git/longhorn-ui/node_modules/open/vendor/xdg-open: 500: gnome-open: not found
```
Due the fact that all NPM packages are outdated, the NPM `open` package (a dependency of `open-browser-webpack-plugin`) is using command line tools that do not exist anymore (gvfs-open or gnome-open) and were replaced by other tools in latest Gnome versions. To get the dev server running on Gnome it is necessary to set the environment variable `DE` to `generic`.
=> Add hint how to run dev server on a Gnome desktop

webpack.config.development.js
Switch to the recommended choice for development builds with high quality source maps. This will simplify debugging in the browser dev tools by providing a 1:1 mapping of the app file structure in the dev tools `Sources` tab.
=> Switch to devtool `eval-source-map`

webpack.config.development.js
- Using the plugin will provide the source maps in the browser as expected. `devtool: "source-map"` does not work somehow.
- Prevent `Error: Invalid URL: webpack://[name]_dll/./node_modules/react-router-dom/es/Link.js` errors in browser when using `devtool: "eval-source-map"`.
Replaces: https://github.com/longhorn/longhorn-ui/pull/612
=> Use `SourceMapDevToolPlugin` instead of `devtool`

webpack.config.development.js
When connecting to a remote Longhorn-manager instance (e.g. running on Digital Ocean), it is necessary that the proxy changes the origin, otherwise all requests are rejected (404).
=> Change origin when using dev server proxy

Dockerfile
It has a permission denied when running UI image to create tempfs directory, copy nginx config files to tempfs directory and open pid file in /run.
But it could be deployed on k8s cluster.
Ref: longhorn/longhorn#6430
=> fix: permission denied when running ui image

nginx.conf.template
According to the nginx docs (http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_types) the MIME type `text/html` does not need to be mentioned.
Fixes: https://github.com/longhorn/longhorn/issues/7002
=> Duplicate MIME type "text/html" in /var/config/nginx/nginx.conf

src/routes/dashboard/components/resourceOverview.js, src/routes/host/DiskList.js, src/routes/host/index.js, src/utils/filter.js
longhorn/longhorn#2238
I originally considered also making AutoEvicting be a separate status from Unschedulable on the Dashboard, but this was too granular of a distinction in my opinion (and the opinion of a couple others I talked to). A user will probably only have one (or a small number) of auto evicting nodes at a time, and the Node tab is a good place to quickly identify it/them.
=> Display AutoEvicting on Node tab while auto evicting

src/routes/backingImage/BackingImageActions.js, src/utils/status.js
Ref: https://github.com/longhorn/longhorn/issues/7288
**Changes**:
It will check `diskFileStatusMap` entries and check if any of the disks are in a ready state. if not, the `Download` button will be disabled.
NOTE: please suggest a better tooltip description that fits into the context.
**Screenshoots**
=> disallows downloading button if disk is not ready

src/routes/engineimage/EngineImageList.js, src/routes/engineimage/detail/EngineImageInfo.js
Check the EngineImage Status with `.status.incompatible` instead of using `EngineImage.state` directly.
Ref: longhorn/longhorn#7683, longhorn/longhorn#7539
=> fix(engineimage): use `EngineImage.status.Incompatible`

src/routes/volume/CreateVolume.js, src/routes/volume/UpdateSnapshotMaxCountModal.js
Ref: https://github.com/longhorn/longhorn/issues/7522
Changes: 
- Improves the tooltip message for `maxCount` so it's clear that 0 means global settings. Fixes the validation so it allows setting 0 back.
- Adds a tooltip for `maxSize` that lets the user know that the size should be at least twice as big as the volume.
=> Adds better messages for the tooltip

src/routes/volume/VolumeActions.js, src/utils/filter.js
Longhorn_ref: https://github.com/longhorn/longhorn/issues/7863
Hides `Upgrade` icon and action for V2 volumes.
=> hides upgrade indicator for v2 volumes

.github/workflows/codespell.yml
Some bot dependency update PRs are blocked by Code spell check for package-lock.json.
- https://github.com/longhorn/longhorn-ui/pull/717
- https://github.com/longhorn/longhorn-ui/pull/717
This PR updates code spell skip item since there is no Golang used in this repo.
=> fix: update code spell skip items

.eslintrc, src/routes/setting/LeaveSettingsModal.js, src/routes/setting/index.js, src/routes/setting/setting.js, src/routes/setting/setting.less
Current general settings page are too long that users easily forget to "save" the settings change before leaving this page.
This PR 
- sticky save button at the bottom
- show modal to alert users there are some unsaved changes when changing the route.
issus : https://github.com/longhorn/longhorn/issues/7497
https://github.com/longhorn/longhorn-ui/assets/5744158/f6cb381d-6b7c-4ebf-86a9-4c81e7c7c831
=> Show modal to alert users the unsaved change in general settings page

src/routes/setting/setting.js, src/routes/setting/setting.less
Fine tune the save button layout in settings page to make it `significant visible` in any browser zoom ratio or small screen.
https://github.com/longhorn/longhorn/issues/7497
My [previous PR](https://github.com/longhorn/longhorn-ui/pull/721) sticky the save button at the buttom of page. 
But it will be unvisible if user zoom into bigger browser ratio (e.g. 100%). This PR makes button all visible to any zoom ratio.
=> fine tune the save button layout in settings page

src/routes/setting/index.js
Fix defect found by QA: https://github.com/longhorn/longhorn/issues/7497#issuecomment-2102212463
if `targetSettingOldValue` is empty string or zero, the original logic won't record the unsaved change.
After fix
https://github.com/longhorn/longhorn-ui/assets/5744158/8e1449c8-2618-4f86-998e-dc267000c45e
=> Correct original empty string won't trigger unsaved modal

src/models/backup.js, src/routes/backup/BackupBulkActions.js, src/routes/backup/BackupVolumeList.js, src/routes/backup/index.js, src/services/backup.js
- Add `Sync Backup Volume` option for each backup volume to allow users to request synchronized backup volume.
- Add `Sync all Backup Volumes` button to sync all backup volumes.
https://github.com/longhorn/longhorn/issues/8501
**Success**
1f2">
---
**Failed**
=> Add sync backup volume option to allow users to manually synchronize backup volume

src/routes/backingImage/DiskStateMapDetail.js, src/routes/volume/index.js, src/utils/filter.js
- Filter out non-ready status backing image in volume create modal dropdown
- Add more backing images disk state colors
Implement extra improvement based on discussion [[IMPROVEMENT] BackingImage UI improvement](https://github.com/longhorn/longhorn/issues/7293#issuecomment-2134688954)
Only let user choose `READY` status backing images
=> Filter out non-ready status backing images in volume create modal dropdown

src/routes/setting/setting.js, src/routes/setting/setting.less
- Add descriptions in danger zone to alert users some settings won't applied immediately ([document](https://longhorn.io/docs/1.7.0/references/settings/#danger-zone))
- Display unapplied settings
https://github.com/longhorn/longhorn/issues/8071
=> Display unapplied danger zone settings in settings page

src/routes/setting/setting.js, src/utils/constants.js, webpack.config.development.js, webpack.config.production.js
From this [PR comment](https://github.com/longhorn/longhorn-ui/pull/735#discussion_r1623752344), we need to let user link to correct version docs following to LH UI version.
Introduce env variable in webpack to know longhorn-ui version at build time.(npm run dev & npm run build)
https://github.com/longhorn/longhorn/issues/8071
**Development mode**
v1.6.3 (by updating version file)
v1.7.0
--------------------------------------------------------------------------------------------------------------------
**Production mode**
Local run `make build` and `make run` to run up longhorn-ui build image
=> Introduce longhorn UI version env variable in webpack

Makefile, README.md
- fix makefile typo 
- add make enter command
- update REDAM.md
Run below commands on my Macbook
- make build : build longhorn-ui image from Dockerfile
- make run :  run up docker container listening on localhost 8000
- make enter : enter container shell
=> Correct makefile typo and add make enter command

src/routes/backingImage/DiskStateMapActions.js
Update backing image clean up disk wordings and modal style  (from writer [suggestion comment](https://github.com/longhorn/website/pull/913#issuecomment-2141440408))
[[IMPROVEMENT] BackingImage UI improvement](https://github.com/longhorn/longhorn/issues/7293)
=> Update backing image clean up disk wordings and modal style

src/components/Snapshot/Snapshot.less, src/routes/volume/detail/ConditionTooltip.js, src/routes/volume/detail/VolumeInfo.js, src/routes/volume/detail/VolumeInfo.less
Backport PR https://github.com/longhorn/longhorn-ui/pull/730 to v1.6.x branch
[[BACKPORT][v1.6.3][IMPROVEMENT] `toomanysnapshots` UI element not prominent enough to prevent runaway snapshots](https://github.com/longhorn/longhorn/issues/8672)
=> [BACKPORT][v1.6.3] toomanysnapshots UI element not prominent enough to prevent runaway snapshots (backport #730)

src/components/Filter/Filter.js, src/models/backingImage.js, src/routes/backingImage/BackingImage.less, src/routes/backingImage/BackingImageActions.js, src/routes/backingImage/BackingImageBulkActions.js, src/routes/backingImage/BackingImageList.js, src/routes/backingImage/DiskStateMapActions.js, src/routes/backingImage/DiskStateMapDetail.js, src/routes/backingImage/index.js, src/routes/volume/index.js, src/services/backingImage.js, src/utils/filter.js
PRs for [[IMPROVEMENT] BackingImage UI improvement](https://github.com/longhorn/longhorn/issues/7293) are implemented in 
- https://github.com/longhorn/longhorn-ui/pull/728
- https://github.com/longhorn/longhorn-ui/pull/729
- https://github.com/longhorn/longhorn-ui/pull/736
- https://github.com/longhorn/longhorn-ui/pull/738
Cherry pick the commits to `v1.6.x` branch.
[[BACKPORT][v1.6.3][IMPROVEMENT] BackingImage UI improvement](https://github.com/longhorn/longhorn/issues/8655)
Test locally
* Acking Image should show the source of it.
* For export-from-volume: volume-name  ✅ 
* For download: url  ✅ 
* For upload: `` (empty)  ✅ 
*  Add filter so user can filter the BackingImage with other properties (e.g. Created From)  ✅ 
*  Bulk download BackingImages  ✅ 
*  BackingImages can show …
=> [BACKPORT][v1.6.3] BackingImage UI improvement (backport mulitple PRs)

src/routes/backup/BulkCreateStandbyVolumeModal.js, src/routes/backup/BulkRestoreBackupModal.js, src/routes/backup/CreateStandbyVolumeModal.js, src/routes/backup/RestoreBackupModal.js, src/routes/backup/index.js
Based on the demo feedback, change
- Remove previous & next buttons. Instead add `Apply All` button for one-click to apply current config to all the others
- Add `encypted option` in Create DR volume bulk action ([discuss thread](https://suse.slack.com/archives/C02DR3N5T24/p1717650221226099?thread_ts=1717649231.597089&cid=C02DR3N5T24))
- Still allow user to click each tab to fill in the restore volume config / DR config
[[IMPROVEMENT] Restore Latest Backup should be applied with BackingImage name value](https://github.com/longhorn/longhorn/issues/7560)
`Restore Latest Backup`
https://github.com/longhorn/longhorn-ui/assets/5744158/fa3103aa-b247-4536-b515-96dcefedacb5
`Create Disaster Recovery Volume`
=> Add Apply All button and encrypted option in Create DR volume bulk action

src/routes/backingImage/CreateBackingImage.js
Replace `it’s` with `it is` because the apostrophe is rendered with a big space with the configured `AvenirNext-Regular` font-family. This is the only occurrence of `it’s` in the whole UI, everywhere else `it is` is used. Perhaps for certain reasons.
https://github.com/longhorn/longhorn/issues/7917
=> Strange placeholder behaviour in input field

src/routes/volume/detail/Snapshots.js
Previous PR mis-delete return in [this.onAction](https://github.com/longhorn/longhorn-ui/pull/760/files#diff-7e98dd20e7b18ef4b96415623c58922f7ef932ca1961d9debda71816a62c2cc0). It causes the code goes to dispatch `snapshotModal/snapshotAction` which is unexpected.
**Reproduce Steps**
- go to volume details page
- click `Create Backup`
https://github.com/longhorn/longhorn/issues/8741
**Fixed**
https://github.com/longhorn/longhorn-ui/assets/5744158/108fda1b-ba51-460f-b53b-bb30fc5374fe
=> Fix unneeded API call got 405 error

src/routes/volume/BulkCloneVolumeModal.js, src/routes/volume/CloneVolume.js
From demo feedback, disable `data engine` when cloning volume.
https://github.com/longhorn/longhorn/issues/8741
**Single Clone Volume**
**Bulk Clone Volume**
=> Disable data engine when cloning volume

src/models/backingImage.js, src/routes/backingImage/BackingImageActions.js, src/routes/backingImage/BackingImageList.js, src/routes/backingImage/CreateBackingImage.js, src/routes/backingImage/UpdateMinCopiesCount.js, src/routes/backingImage/index.js, src/routes/host/DiskList.js, src/routes/host/HostList.js, src/routes/host/components/TagComponent.js, src/routes/volume/detail/VolumeInfo.js, src/routes/volume/index.js, src/services/backingImage.js, src/utils/constants.js, src/utils/dataDependency.js
https://github.com/longhorn/longhorn/issues/8485
https://github.com/longhorn/longhorn-ui/assets/5744158/f9cb1282-107d-49a4-baa3-12a51386493b
=>  Add new feilds to backing image table and creation modal 

src/models/volume.js, src/routes/volume/index.js
In previous [PR](https://github.com/longhorn/longhorn-ui/pull/766), I didn't notice there is bulk `Create Backup` action in volume page, we should bring `backupMode` in payload as well.
https://github.com/longhorn/longhorn/issues/8947
=> fix: bring backupMode in volume/bulkBackup payload

src/models/snapshot.js, src/routes/volume/detail/Snapshots.js
Same as https://github.com/longhorn/longhorn-ui/pull/768, should bring `backupMode` field in payload.
[[BUG] Create backup from UI volume page failed](https://github.com/longhorn/longhorn/issues/8947)
https://github.com/longhorn/longhorn-ui/assets/5744158/52466c69-e8d1-42aa-a190-7858a3640a77
=> fix take backup from snapshot should bring backupMode in payload

.eslintrc, .stylelintrc, src/components/Filter/Filter.js, src/components/Layout/Footer.js, src/models/backingImage.js, src/models/backup.js, src/models/systemBackups.js, src/routes/backingImage/BackingImage.less, src/routes/backingImage/BackingImageActions.js, src/routes/backingImage/BackingImageBulkActions.js, src/routes/backingImage/BackingImageList.js, src/routes/backingImage/BackupBackingImageActions.js, src/routes/backingImage/BackupBackingImageBulkActions.js, src/routes/backingImage/BackupBackingImageList.js, src/routes/backingImage/DiskStateMapDetail.js, src/routes/backingImage/RestoreBackupBackingImageModal.js, src/routes/backingImage/index.js, src/routes/systemBackups/index.js, src/routes/volume/CreateVolume.js, src/services/backingImage.js, src/utils/dataDependency.js, src/utils/sort.js, src/utils/websocket.js
Other minor changes
- Add BackupBackingImages websocket icon on the right bottom corner
- Refactor duplicated logic to single one function
- Fix typo
[[FEATURE] Add BackupBackingImage UI](https://github.com/longhorn/longhorn/issues/7541)
[[UI][FEATURE] Add backing image encryption and clone support](https://github.com/longhorn/longhorn/issues/8789)
**Backup BI and restore BBI**
https://github.com/longhorn/longhorn-ui/assets/5744158/58e74eb8-197d-40db-be15-421a7c0c72fb
**Search BI and BBI tables**
https://github.com/longhorn/longhorn-ui/assets/5744158/34ecab14-4d12-430e-95ca-55ffffd6fb2e
**Bulk backup BI**
https://github.com/longhorn/longhorn-ui/assets/5744158/f26a8f47-b9e6-43dd-96b7-b0049f37a31f
Try this PR using `a110605/longhorn-ui:0709issue7541amd64`
=> Add backup backing image table

src/models/backup.js, src/routes/backingImage/BackingImageActions.js, src/routes/backingImage/BackingImageBulkActions.js, src/routes/backingImage/BackingImageList.js, src/routes/backingImage/index.js, src/routes/systemBackups/index.js, src/routes/systemBackups/systemBackupsBulkActions.js, src/utils/dataDependency.js
Since bbi table is added in backing image page in previous PR.
We should show `backup target URL is empty` error message in backup, backingImage or systemBackups pages and disable related buttons.
https://github.com/longhorn/longhorn/issues/7541
Empty backuptarget
https://github.com/longhorn/longhorn-ui/assets/5744158/9ffd0baf-dd86-47c0-850e-2933ce673dea
Availalbe backuptarget
https://github.com/longhorn/longhorn-ui/assets/5744158/050b8273-fd14-4317-b472-de1a34271e39
If user input non-available backuptarget, couldn't connect it or typo.
The error msg too long to read. Maybe we can simple it to one sentence like `backup target is not available` cc @ChanYiLin
=> show error message and disable buttons if backup target is not available

src/components/Snapshot/Snapshot.js, src/models/backingImage.js, src/routes/backingImage/BackingImageActions.js, src/routes/backingImage/BackingImageBulkActions.js, src/routes/backingImage/RestoreBackupBackingImageModal.js, src/routes/backingImage/index.js
From doc review feedback, update the wordings. 
See https://github.com/longhorn/website/pull/943#issuecomment-2224851099
https://github.com/longhorn/longhorn/issues/7541
In volume detail page.
This PR should backport to v1.7.x
=> Update backup wording and restore backing image modal

src/models/instanceManager.js
The bug comes from currentState : "running" is lowercase. but user searches "Running"
Ignore case sensitive when search in instance manager image page
https://github.com/longhorn/longhorn/issues/9010
https://github.com/user-attachments/assets/91005490-2f3a-4a5c-bd62-305a399d7bd6
Note. this PR need backport to v1.7.x once merged
=> ignore case sensitive when search in instance manager image page

src/routes/volume/VolumeBulkActions.js, src/routes/volume/index.js
- filter out volumes in restoring or not ready status when click bulk clone volume
- disable bulk clone volume button if all selected vols are in restoring or not ready status 
https://github.com/longhorn/longhorn/issues/9016
https://github.com/user-attachments/assets/7779a96a-f618-452c-8e23-c9aae69adb85
Note. this PR need backport to v1.7.x
=> filter out volume in restoring or not ready status when bulk clone volume

src/models/volume.js, src/routes/volume/CreateVolume.js, src/routes/volume/VolumeActions.js, src/routes/volume/VolumeBulkActions.js, src/routes/volume/VolumeList.js, src/routes/volume/detail/VolumeInfo.js, src/routes/volume/detail/index.js, src/routes/volume/helper/index.js, src/routes/volume/index.js
Remove offline replica rebuilding related info and settings
- alert in volume detail page
- volume info in volume detail page
- options in create volume modal
- update modal, action button and bulk action in volume / volume detail page
- volume state tooltip
[[IMPROVEMENT] Remove Offline Rebuilding from UI on master and v1.7.0](https://github.com/longhorn/longhorn/issues/9090)
Remove below UI components
Note. this PR will backport to v1.7.x after merged.
=> Remove offline replica rebuilding UI components

src/routes/volume/CreateVolume.js, src/routes/volume/detail/index.js, src/routes/volume/helper/index.js, src/routes/volume/index.js
Fix : lowercase options name in volume page
https://github.com/longhorn/longhorn/issues/8786#issuecomment-2339555684
[lowercase_options.webm](https://github.com/user-attachments/assets/76d45784-b222-498a-ae56-50030d73f435)
[lowercase_bulk_action.webm](https://github.com/user-attachments/assets/82348fa3-923c-4ed5-b305-4fc9a326336d)
=> fix: lowercase options name in volume page

src/routes/host/components/EditableDiskItem.js, src/routes/host/components/EditableDiskItem.less, src/routes/host/components/EditableDiskList.js
fix: align the disk/node conditions in a vertical way.
https://github.com/longhorn/longhorn/issues/9629
Add mock data in `disk.conditions` and `node.conditions`
=> fix: align the disk/node conditions in a vertical way

src/routes/volume/detail/VolumeInfo.js, src/routes/volume/detail/VolumeInfo.less
Backport of PR for v1.7.x. 
The original PR can be found at: https://github.com/longhorn/longhorn-ui/pull/825.
[[UI][IMPROVEMENT] Improve the volume size information on UI #8843
](https://github.com/longhorn/longhorn/issues/8843)
N/A
=> feat: improve the volume size information on UI

src/routes/backingImage/BackupBackingImage.js, src/routes/backingImage/CreateBackingImage.js, src/routes/backingImage/RestoreBackupBackingImageModal.js, src/routes/backingImage/index.js, src/routes/backup/BulkCreateStandbyVolumeModal.js, src/routes/backup/BulkRestoreBackupModal.js, src/routes/backup/CreateStandbyVolumeModal.js, src/routes/backup/RestoreBackupModal.js, src/routes/backup/index.js, src/routes/volume/BulkCloneVolumeModal.js, src/routes/volume/CreateVolume.js
[[UI][FEATURE] Support V2 Backing Image in UI #9880](https://github.com/longhorn/longhorn/issues/9880#issuecomment-2559501498)
- Create a `parrot` backing image with `Data Engine: v1`
- Backup then delete the `parrot` backing image
- Restore the backup `parrot` with `Data Engine: v1`
- Observe that `parrot` is restored, then delete again
- Restore the backup `parrot` with `Data Engine: v2`
- Observe that `parrot` is restored, then delete again
- Navigate to `http://localhost:8080/#/backup#backing-image`
- Restore the backup `parrot` with `Data Engine: v1`
- Navigate to `http://localhost:8080/#/backingImage`, Observe that `parrot` is restored
https://github.com/user-attachments/assets/b1f7cc00-ee68-4509-b9c7-f6cd53e4d12e
Test with `LONGHORN_MANAGER_IP=http://159.89.205.43:30001/ npm run …
=> feat: support restore v2 backing image

src/routes/volume/VolumeBulkActions.js
fix: disable bulk Create Backup button if any volume is detached
https://github.com/longhorn/longhorn/issues/10460
If all volumes are attached, enable button
If any volume is detached, disable button
=> fix: disable bulk create backup button if any volume is detached

src/routes/volume/CreateVolume.js, src/routes/volume/helper/index.js
- Add the `Frontend` options during volume creation based on the selected data engine version
- Display the `Frontend` setting `UBLK` on the volume details page
[[TASK] [UI] [FEATURE] v2 volume supports UBLK frontend #10735](https://github.com/longhorn/longhorn/issues/10735#issuecomment-2817729136)
1. Ensure the `UBLK` kernel module is loaded on each node by running `modprobe ublk_drv`
2. Navigate to the volume page and click on `Create Volume`
3. In the popup modal:
- For `v1` data engine, only the following `Frontend` options should be available:
- `Block Device`
- `iSCSI`
- For `v2` data engine, the following `Frontend` options should be available:
- `Block Device`
- `NVMf `
- `UBLK`
4. Select the `v2` data engine and choose `UBLK` as the frontend
5. Attach the volume, it should attach …
=> feat: v2 volume supports UBLK frontend

src/routes/orphanedData/index.js, src/utils/menu.js
Change the wording based on demo feedback
- Rename the `Orphaned Data` page
- Update the tabs to remove the term `orphans`
N/A
N/A
=> refactor: change Orphaned Data page wordings

src/components/Layout/Menu.js, src/utils/menu.js
- Restructure the menu to make it easier for users to find pages
- Remove icons from menu
- Used consistent plural forms for clarity
[[IMPROVEMENT] Orphaned Data should not be placed under Settings #10383](https://github.com/longhorn/longhorn/issues/10383)
New page structures
- Dashboard
- Nodes
- Volumes
- Recurring Jobs
- Backup and Restore
- Backups
- Backup Targets
- System Backups
- Advanced
- Backing Images
- Orphaned Resources
- Engine Images
- Instance Manager Images
- Settings
**Top level menu**
**Backup and Snapshots**
**Advanced**
N/A
=> feat: restructure the navigation menus

src/models/backup.js, src/routes/backupTarget/BackupTargetList.js, src/routes/backupTarget/BackupTargetList.less
- Add tooltip to display more detailed messages
[[IMPROVEMENT] useful error message from /v1/backuptargets is not displayed in UI #10428](https://github.com/longhorn/longhorn/issues/10428)
- Navigate to Backup Target page
- If there's an error, show an `Error` with a tooltip that displays a helpful message on hover
- If there's no error, the tooltip should NOT appear
Sometimes the message is unreadable, this will be improved on the backend side. ([issue #11389](https://github.com/longhorn/longhorn/issues/11389))
=> feat: useful error message from /v1/backuptargets is not displayed in UI

src/models/backup.js, src/routes/backup/BackupDetail.js, src/routes/backup/BackupVolume.js, src/routes/backup/BulkCreateStandbyVolumeModal.js, src/routes/backup/BulkRestoreBackupModal.js, src/routes/backup/CreateStandbyVolumeModal.js
- Add `Backup Block Size` for DR volume
[[FEATURE] UI supports configurable volume backup block size #11351](https://github.com/longhorn/longhorn/issues/11351)
- Navigate to the backup page and click `Create Disaster Recovery Volume`
- Confirm that the `Backup Block Size` is read-only in the modal and its value matches the source volume (latest backup)
https://github.com/user-attachments/assets/b5ec6ced-55cb-45b1-b499-8b82bacc9b4d
Related PR: https://github.com/longhorn/longhorn-ui/pull/948
=> fix: UI supports configurable volume backup block size

Dockerfile, nginx.conf.template, scripts/start-nginx.sh
Conditionally enables IPv6 listening in the Longhorn UI Nginx container. This ensures the container works correctly on both IPv4-only and dual-stack networks.
longhorn/longhorn#11869
=> fix: conditionally enable IPv6 listening
